### ISSUE TITLE
Setup initial structure

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#1]
Een eerste stap lijkt mij het uitwerken van een ruwe repo structuur waarin we reeds enkele files (zoals bvb de vertaalsleutel, dockerfile, ...) kunnen plaatsen.

**Comment by mvarewyck** [comment]
Ivm vertaalsleutel: File hiervoor vind je terug in [extdata](https://github.com/inbo/alien-species-portal/tree/main/alienSpecies/inst/extdata) foilder

Er bestaat een R-package voor auto-vertalingen van labels [datamods](https://dreamrs.github.io/datamods/articles/i18n.html) maar dit ondersteunt geen Nederlands.

**Comment by SanderDevisscher** [comment]
De initiele structuur is aangemaakt => deze issue mag dicht ?
