### ISSUE TITLE
Failing github actions

### ISSUE THREAD

**Issue by mvarewyck** [inbo/alien-species-portal#102]
When we trigger a [docker build](https://github.com/inbo/alien-species-portal/actions/runs/9397717299) it is always failing while for @TheJenne18 it is not.
@TheJenne18 
* what are you doing differently? 
* can you configure caching of the image?

**Comment by TheJenne18** [comment]
@mvarewyck are their any optimalisations for downloading R packages because the R packages are taking up to an hour (downloading and compiling).

I just trigger a re-run in github actions. So I don't do anything special.

**Comment by mvarewyck** [comment]
> @mvarewyck are their any optimalisations for downloading R packages because the R packages are taking up to an hour (downloading and compiling).
> 
Yes, this can be overcome [as mentioned earlier](https://github.com/inbo/alien-species-portal/pull/74#issuecomment-2122667773) by moving to `intel` which allows you to install compiled R packages, so no compilation is needed then.

**Comment by mvarewyck** [comment]
@TheJenne18 Any news/feedback on this? The builds are still failing.

**Comment by TheJenne18** [comment]
@mvarewyck possible fix has been deployed. We launched a new action based on the last failed one: [https://github.com/inbo/alien-species-portal/actions/runs/9397717299](https://github.com/inbo/alien-species-portal/actions/runs/9397717299)

**Comment by TheJenne18** [comment]
After our changes on the runner infra, the github action was finished with success
