### ISSUE TITLE
Create report fails on exoten-uat.inbo.be

### ISSUE THREAD

**Issue by mvarewyck** [inbo/alien-species-portal#104]
Should be fixed :
- [ ] clicking `create report` results in a timeout

_Originally posted by @SanderDevisscher in https://github.com/inbo/alien-species-portal/pull/74#pullrequestreview-2082509713_

**Comment by mvarewyck** [comment]
@TheJenne18 Can we read out the error logs from exoten-uat.inbo.be (Error triggered today at 17h)? If not, can I pull the docker image that is being used at exoten-uat.inbo.be?

Given that it fails immediately when pushing the button, I think some dependency is missing in the docker image. Locally, I can build a docker image for amd64 and there it doesn't fail to render the report.
I can't build a docker image for arm64 on my pc smoothly. So, if you can't read out the error message, I will have to spend some extra time to make this build work locally.

**Comment by SanderDevisscher** [comment]
@TheJenne18 can you provide the necessary logs to @mvarewyck ?

**Comment by TheJenne18** [comment]
logs are send by mail

**Comment by mvarewyck** [comment]
Thanks @TheJenne18 but I need other log files, namely from the app. The container starts correctly and also the app starts up correctly, it is within the app/container that sth goes wrong; not locally or in my docker container, only in the online version.

**Comment by TheJenne18** [comment]
I've send it again

**Comment by mvarewyck** [comment]
Sth goes wrong with webshot, I have to investigate

`Warning: Error in <Anonymous>: webshot.js returned failure value: 2`

**Comment by mvarewyck** [comment]
We need to move to `webshot2` instead of `webshot` as there is no phantomjs available for ubuntu22.04
