### ISSUE TITLE
[Feature request] add link to Harmonia+ db

### ISSUE THREAD

**Issue by mvarewyck** [inbo/alien-species-portal#105]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Include a link to the harmonia+ db as provided [here](https://github.com/inbo/aspbo/issues/166)
@SanderDevisscher @soriadelva where to put this link on the alien species page?

**Comment by soriadelva** [comment]
> **Is your feature request related to a problem? Please describe.** No
> 
> **Describe the solution you'd like** Include a link to the harmonia+ db as provided [here](https://github.com/inbo/aspbo/issues/166) @SanderDevisscher @soriadelva where to put this link on the alien species page?

@mvarewyck if I remember correctly the idea was to put this under species information, under the tab "more"

**Comment by mvarewyck** [comment]
> > **Is your feature request related to a problem? Please describe.** No
> > **Describe the solution you'd like** Include a link to the harmonia+ db as provided [here](https://github.com/inbo/aspbo/issues/166) @SanderDevisscher @soriadelva where to put this link on the alien species page?
> 
> @mvarewyck if I remember correctly the idea was to put this under species information, under the tab "more"

In the 'Links' tabpage then, on top of the potential Rmd you created? Or the 'Risk assessment' page?

![Screenshot from 2024-07-08 14-06-10](https://github.com/inbo/alien-species-portal/assets/22143743/1d140102-71a8-42d0-960b-19d1955d6da9)

**Comment by soriadelva** [comment]
> > > **Is your feature request related to a problem? Please describe.** No
> > > **Describe the solution you'd like** Include a link to the harmonia+ db as provided [here](https://github.com/inbo/aspbo/issues/166) @SanderDevisscher @soriadelva where to put this link on the alien species page?
> > 
> > 
> > @mvarewyck if I remember correctly the idea was to put this under species information, under the tab "more"
> 
> In the 'Links' tabpage then, on top of the potential Rmd you created? Or the 'Risk assessment' page?
> 
> ![Screenshot from 2024-07-08 14-06-10](https://private-user-images.githubusercontent.com/22143743/346555052-1d140102-71a8-42d0-960b-19d1955d6da9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDM0NjEsIm5iZiI6MTcyMDQ0MzE2MSwicGF0aCI6Ii8yMjE0Mzc0My8zNDY1NTUwNTItMWQxNDAxMDItNzFhOC00MmQwLTk2MGItMTlkMTk1NWQ2ZGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEyNTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMjI4OWU2ZGIwY2M2OWRlNDdiNWIwNDE4ZmNhOTdiYjFhNzgwNDZhZDU0M2UxNjc4MWY0NWVjY2Y2ODdlMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._MqP8D2PGzQdaFl5Y_z1zgRFjGnmYVY-Vowt4p1fn7I)

Good question, @SanderDevisscher what do you think? In essence, Harmonia+ is a risk assessment scheme but if we're only providing the link it may be more appropriate to put it under "links"?

**Comment by SanderDevisscher** [comment]
My Idea was to embed the relevant Harmonia+ under risk assessment. If this is not recommended a link under links will suffice.

**Comment by mvarewyck** [comment]
The website https://ias.biodiversity.be/species/ currently doesn't allow to embed it on other webpages. 
`Refused to frame 'https://ias.biodiversity.be/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".` It could be changed on the biodiversity website, see [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors).

For now, I'll include the link under links page.

**Comment by SanderDevisscher** [comment]
ok for me
