### ISSUE TITLE
[BUG] wrong datatype? in graph below observation map

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#106]
**Location of the bug**
Provide a location of where the bug occured.
Species Information > Observations > graph below observation map

**Describe the bug**
Instead of a graph the following message is displayed:
```
Column or expression 2 of 'by' or 'keyby' is type 'NULL' which is not currently supported. 
If you have a compelling use case, please add it to https://github.com/Rdatatable/data.table/issues/1597. 
As a workaround, consider converting the column to a supported type, e.g. by=sapply(list_col, toString), whilst taking care to maintain distinctness in the process.
```

**To Reproduce**
1. Go to 'exoten-uat.inbo.be'
2. Click on 'Species Information'
3. Select any species with observations
4. Scroll down
5. See error

**Expected behavior**
The graph is displayed 

**Screenshots**
![image](https://github.com/user-attachments/assets/33399624-1e8f-4ad5-871f-20cb78010e71)

**Additional context**
This issue was first noticed after https://github.com/inbo/aspbo/pull/202

**Comment by mvarewyck** [comment]
I quickly checked. With the old data there was a merge required to attach columns 
`"isFlanders"   "isWallonia"   "isBrussels"` but this step is redundant now. 
It was creating the columns twice, with a suffix, so not recognized by the plot anymore.
I'll check whether this data change also affects other parts of the code.
