### ISSUE TITLE
[Enhancement] Taxonkey shown under checklist indicators - Taxa does not correspond to the GBIF taxonkey.

### ISSUE THREAD

**Issue by soriadelva** [inbo/alien-species-portal#109]
**Location of enhancement**
Checklist indicators > Taxa > Taxa table

**Description**
The GBIF taxonomic ID (taxonkey) does not correspond to the actual taxonkey of the GBIF backbone but to the taxonkey of this species in a checklist of alien species in Belgium (indicated under source). However, the column name indicates that this should be the GBIF taxonkey, and also in the title of the GAMs the GBIF taxonkey is shown.

**Suggestion how to implement change**
 I would either change the name of this column to checklist taxonkey (or something alike) or I would change the taxonkey to the accepted taxonkey of the species in the GBIF backbone. The latter key is already indicated on the GAMs so this option would have my preference.

**Comment by mvarewyck** [comment]
@soriadelva Just as a double check for *Gyrodactylus proterorhini*
* GBIF key : 5740285
* Link : https://www.gbif.org/species/164300887 

Or do we need to change also the link to: https://www.gbif.org/species/5740285
(both pages exist, but the first page is as in the data source "data_input_checklist_indicators.tsv"; 2nd we need to construct in the code/backend)

**Comment by mvarewyck** [comment]
Meeting: decided to update the links too
