### ISSUE TITLE
Create Taxa table

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#11]
Deze tabel zou moeten worden weergeven onder het Taxa - tabblad.
![image](https://user-images.githubusercontent.com/16779320/143581111-ad7f34f8-83c5-4238-a487-0cfc0d4a9d9b.png)

De tabel wordt gevoed vanuit de GRIIS - checklist, gefilterd door de keuzes van de gebruiker. 
De tabel moet de volgende kolommen bevatten:
- Species: Soortnaam in het latijn
- Common names: Soortnaam in de gekozen taal (NL, EN, FR)
- Gbif taxonkey: de taxonkey van gbif die fungeert als hyperlink naar de pagina van de soort (`https://www.gbif.org/species/%taxonkey%`)
- Year of first introduction: jaar van eerste introductie in de regios (BEL, VLA, BXL, WAL)<sup>1</sup>
- Last date of observation: de laatste observatie in de gekozen regio (default BEL)
- Habitat: habitat van de soort
- CBD Pathways: De cbd pathways van een soort weergegeven als `lvl1_pathway1:lvl2_pathway1; lvl1_pathway2:lvl2_pathway2`
- Degree of establishment:
- Source:
- More: Een verkeerlicht <sup>2</sup> en een icoontje <sup>3</sup> voor unielijst soorten waarmee de gebruiker in 1 opzicht kan zien hoeveel soort specifieke info er is. Overigens fungeert dit verkeerslicht als link naar de soortspecifieke pagina. 

<sup>1</sup> De vier regios (BEL, VLA, BXL, WAL) worden altijd weergegeven ook wanneer ze er "nog" niet voorkomen. In het geval van afwezigheid word `NA` weergegeven bij de betreffende regio. Belangrijk gegeven hier is dat de Year of first introduction van  andere regios ook weergegeven wordt ook al worden deze niet geselecteerd. De regio filter dient dus enkel om soorten te filteren die in een bepaalde regio voorkomen en niet om de data op zich te filteren.  

<sup>2</sup> Mijn voorstel is om de volgende "logica" te volgen:
- Groen: Observations, Succesvolle GAMs, (Reporting,) Management 
- Oranje: Observations, (Reporting) & minstens 1 succesvolle GAM of Management
- Rood of Zwart: Enkel Observations & (Reporting)

<sup>3</sup> ik stel voor hiervoor iets in deze aard te gebruiken:
![noun_europe_2430585](https://user-images.githubusercontent.com/16779320/143589145-75c86c12-3029-4872-b9da-c67df40b86e3.png)

**Comment by mvarewyck** [comment]
Icons have been added. Using an icon from a gallery, it's most easily to change the color.
For lists of available icons, see http://fontawesome.io/icons/ and http://getbootstrap.com/components/#glyphicons.
In case of using a png/jpg instead of an icon, we need a separate file per color.

Icon color is currently always black. Code for updating the color is ready. We still need to implement in the table which color should be passed to the icons. 
TBD: E.g. succesvolle GAMs therefore we need to fit the GAMs for all species beforehand? No management data yet.
