### ISSUE TITLE
[BUG] Year of first observation in Belgium indicated in the taxa table under checklist indicators is not always correct

### ISSUE THREAD

**Issue by soriadelva** [inbo/alien-species-portal#110]
**Location of the bug**
Checklist indicators>Taxa>Taxa table

**Describe the bug**
For some species (example Abies alba), the year of first observation in Belgium is later than the year of first observation in Wallonia or Flanders, which does not make sense.
 
**Screenshots**
![Year_of_first_observation](https://github.com/user-attachments/assets/6b6164ba-e37d-4e24-a8a4-a0f61497ae19)

**Comment by mvarewyck** [comment]
@soriadelva This comes directly from the aspbo data/trias project: https://github.com/inbo/aspbo/blob/uat/.github/PR_download_griis_checklist.md

```
dataFile <- "~/git/aspbo/data/output/UAT_processing/data_input_checklist_indicators.tsv"
rawData <- data.table::fread(dataFile, stringsAsFactors = FALSE, na.strings = "")
rawData[rawData$species == "Abies alba", c("locality", "first_observed", "last_observed")]
#          locality first_observed last_observed
# 1:        Belgium           2008          2017
# 2: Flemish Region           2008          2017
# 3: Walloon Region           2005          2022
```

**Comment by SanderDevisscher** [comment]
actually its a bug in the GRIIS checklist see https://www.gbif.org/species/152546516/verbatim under `Species Distribution`.

I'll add an issue in the [unified checklist](https://github.com/trias-project/unified-checklist) repo

**Comment by SanderDevisscher** [comment]
see https://github.com/trias-project/unified-checklist/issues/87
