### ISSUE TITLE
[BUG] The app crashes when you go to Checklist indicators >Trend,Pathways, or Origin 

### ISSUE THREAD

**Issue by soriadelva** [inbo/alien-species-portal#115]
**Location of the bug**
Checklist indicators>Trend, Pathways, or Origin

**Describe the bug**
The app crashes whenever you want to go to another subtab than taxa (i.e., Trend, Pathways, or Origin) under Checklist indicators.

**Reproduce bug**
1. Go to 'Checklist indicators'
2. Click on 'Trend', 'Pathways', or 'Origin'
3. See that the app crashes

**Screenshots**
![crash](https://github.com/user-attachments/assets/07072712-6a62-4c6b-8e4d-d507f4b955fb)

**Comment by mvarewyck** [comment]
On a side note: I forced in data 'indicators' the variables 'first_observed' and 'last_observed' to be numeric. Fix already implemented here: https://github.com/inbo/alien-species-portal/blob/fix_v1.1.0/alienSpecies/R/data_create.R#L467-L468
