### ISSUE TITLE
[BUG] Number of bins is too large

### ISSUE THREAD

**Issue by mvarewyck** [inbo/alien-species-portal#118]
**Location of the bug**

Species Information > Indicators > Invasion history of Abies alba (2023)

**Describe the bug**

When selecting 'Edit classes' and 'Uniform' it fails to create the classes.
This is because in the data, only values 1 and 2 occur, so the largest number of unique classes/breaks that can be created with these data is 2.
Currently a red error is displayed.

**Expected behavior**

@SanderDevisscher @soriadelva How should we handle this case?

* Allow number of bins to be 2?
* Replace the red error by a message to force the user to choose another way to create the bins?
* Show only 2 groups even though the user chose a larger value for no. of groups?

**Screenshots**

![Screenshot from 2024-09-27 09-55-45](https://github.com/user-attachments/assets/db5936bd-1022-4122-8913-55efd8d293de)
![Screenshot from 2024-09-27 09-55-32](https://github.com/user-attachments/assets/6a185139-a7d5-41ad-a8d1-649c47bf12f9)

**Version**

GIT commit 92d5b81

**Comment by SanderDevisscher** [comment]
I would limit the number of allowed groups to be max(values) when the max value is below 8 else the number of groups should be 8 always.
