### ISSUE TITLE
Create Pathway indicators

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#13]
Deze tabel en grafieken zijn worden allen gemaakt door functies uit het [Trias package](https://github.com/trias-project/trias) en werden reeds rudimentair toegevoegd aan de exoten pagina van de grofwild app (zie [inbo/reporting-rshiny-grofwildjacht@exoten](https://github.com/inbo/reporting-rshiny-grofwildjacht/tree/exoten)). De data manipulatie die nodig is voor deze grafieken obv de GRIIS checklist staat in deze [tutorial](https://trias-project.github.io/indicators/01_get_data_input_checklist_indicators.html). Meer info omtrent de indicator vind je terug op de [Trias indicatoren pagina](https://trias-project.github.io/indicators/04_indicator_pathways.html)

Het gaat hier over deze indicators:
- de tabel Introduction pathways per category 
![image](https://user-images.githubusercontent.com/16779320/143610387-7f692b86-ce98-43dc-b0c5-4b7ebb0268bb.png)

- CBD Level 1 introduction pathways (`trias::visualize_pathways_level1()`)
![image](https://user-images.githubusercontent.com/16779320/143610889-9669a5da-cc87-4e10-a13d-591d6203d1c0.png)

- CBD Level 1 introduction pathways - trends (`trias::visualize_pathways_year_level1()`)
![image](https://user-images.githubusercontent.com/16779320/143610933-f0e646e6-6d81-4fec-bf92-5fbf97093d87.png)

- CBD Level 2 introduction pathways (`trias::visualize_pathways_level2()`)
![image](https://user-images.githubusercontent.com/16779320/143610972-510de762-ed64-4904-ae52-e53ea1465321.png)

Het eindproduct moeten een tabel en 3 plotly grafieken zijn.

**Comment by mvarewyck** [comment]
For the trias functions the data slot is still missing for downloading the summarized data as shown in the plot.
Current download returns the raw input data for the trias plot.
