### ISSUE TITLE
Live app IAS_Species_Dashboard

### ISSUE THREAD

**Issue by mvarewyck** [inbo/alien-species-portal#19]
Do you happen to have this app running online (rsconnect?) and grant me access to it?
I tried to run it locally but it keeps loading and does not start up.
I can dig into the code, but it would be easier if I could explore via the app.

**Comment by SanderDevisscher** [comment]
I had to scrap the shinyapps.io since I'm limited to only 5 shinyapps for free :-/

**Comment by SanderDevisscher** [comment]
https://iasspeciesdashboard.shinyapps.io/all_species_dashboard/
