### ISSUE TITLE
Implement new trias features

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#20]
@mvarewyck changes to the trias package concerning the exporting of the data used to make the indicator graphs has just been approved (see [PR 87](https://github.com/trias-project/trias/pull/87)). If you update/reinstall the trias package the [indicator_introduction_year()](https://trias-project.github.io/indicators/02_indicator_introductions_per_year.html) & [indicator_total_year()](https://trias-project.github.io/indicators/03_indicator_cumulative_number.html) - indicators should now export 2 dataslots containing the data used to make the graphs, named: `data_top_graph` & `data_facet_graph` and 1 plot slot containing the plot, named `plot`.  This should enable the downloading of the data used. Can you update the flow to accommodate the changes?

**Comment by mvarewyck** [comment]
Works fine now for these 2 functions.
Still missing for the pathway functions: See [comment](https://github.com/inbo/alien-species-portal/issues/13#issuecomment-1170061964)

**Comment by mvarewyck** [comment]
Fixed for pathway functions
