### ISSUE TITLE
Provide source links

### ISSUE THREAD

**Issue by mvarewyck** [inbo/alien-species-portal#22]
Related to #8 

For the source links I need the correct webpage URLs. Currently I only know it for WRiMS. Could any of you please complete the list?

- [x] "Ad hoc alien species checklist" 
- [x] "Alien Bird Checklist"          
- [x] "Alien Fish Flanders"
- [x] "Alien Macroinverts"            
- [x] "Alien Mollusc checklist"
- [x] "Belgian rust fungi"            
- [x] "Manual of Alien Plants"         
- [x] "RINSE1"                        
- [x] "RINSE2"
- [x] "WRiMS" https://www.marinespecies.org/           

For my reference: To be completed [here](https://github.com/inbo/alien-species-portal/blob/mockup/alienSpecies/R/data_load.R#L183-L187)

**Comment by timadriaens** [comment]
they should all be easily found through the TrIAS community page https://www.gbif.org/network/b153643d-735a-440f-a0e9-428b4f9d1cd2/dataset

**Comment by mvarewyck** [comment]
Can I just refer to the GBIF datasets page then? E.g. for 
"Add hoc alien species checklist" https://www.gbif.org/dataset/1f3505cd-5d98-4e23-bd3b-ffe59d05d7c2

**Comment by SanderDevisscher** [comment]
I would say for those available on gbif => YES

**Comment by mvarewyck** [comment]
What's the difference between RINSE1 and RINSE2? Guessing right now which one is 1 and 2..

Current links:
            "Ad hoc alien species checklist" = "https://www.gbif.org/dataset/1f3505cd-5d98-4e23-bd3b-ffe59d05d7c2",
              "Alien Bird Checklist" = "https://www.gbif.org/dataset/e1c3be64-2799-4342-8312-49d076993132",
              "Alien Fish Flanders" = "https://www.gbif.org/dataset/98940a79-2bf1-46e6-afd6-ba2e85a26f9f",
              "Alien Macroinverts" = "https://www.gbif.org/dataset/289244ee-e1c1-49aa-b2d7-d379391ce265",
              "Alien Mollusc checklist" = "https://www.gbif.org/dataset/e082b10e-476f-43c1-aa61-f8d92f33029a",
              "Belgian rust fungi" = "https://www.gbif.org/dataset/b043c480-dd36-4f4f-aa82-e188753ff09d",
              "Manual of Alien Plants" = "https://www.gbif.org/dataset/9ff7d317-609b-4c08-bd86-3bc404b77c42",
              "RINSE1" = "https://www.gbif.org/dataset/1738f272-6b5d-4f43-9a92-453a8c5ea50a",
              "RINSE2" = "https://www.gbif.org/dataset/3f5e930b-52a5-461d-87ec-26ecd66f14a3",
              "WRiMS" = "https://www.gbif.org/dataset/0a2eaf0c-5504-4f48-a47f-c94229029dc8")

**Comment by timadriaens** [comment]
Good question, one of those has over 6000 records, the other just has 359, maybe you can check? Otherwise, best to ask Lien Reyserhove because it has been so long ago I don't remember well. @SanderDevisscher can you add Lien to the repo so we can ping her?

**Comment by SanderDevisscher** [comment]
@LienReyserhove has been added

**Comment by SanderDevisscher** [comment]
Looking at the publication/modification dates I would presume this one https://www.gbif.org/dataset/3f5e930b-52a5-461d-87ec-26ecd66f14a3 is RINSE 1 (May 15, 2019) & this one https://www.gbif.org/dataset/1738f272-6b5d-4f43-9a92-453a8c5ea50a would be RINSE 2 (May 11, 2021) then ?

**Comment by timadriaens** [comment]
@LienReyserhove can you confirm?

**Comment by LienReyserhove** [comment]
I don't think I can be of any help here. I know the link between the original dataset and the publication on GBIF, but I have no idea who and on what basis it whas decided to assign the names "RINSE 1" and "RINSE 2" to the datasets. I'm lacking context for this

- RINSE pathways: [dataset on GBIF](https://doi.org/10.15468/guejza), [original dataset](https://doi.org/10.1007/s10530-016-1278-z), 359 species names 
- RINSE registry: [dataset on GBIF](https://doi.org/10.15468/focajn), [original dataset](https://doi.org/10.3897/neobiota.23.5665), 6643 species names

**Comment by mvarewyck** [comment]
Implemented as in https://github.com/inbo/alien-species-portal/issues/22#issuecomment-1175170162
