### ISSUE TITLE
Check GBIF keys/source

### ISSUE THREAD

**Issue by mvarewyck** [inbo/alien-species-portal#23]
To create the link to the GBIF record I currently use the gbif link in the source-column from the [indicators dataset](https://github.com/inbo/alien-species-portal/blob/mockup/alienSpecies/inst/extdata/data_input_checklist_indicators.tsv)

(1) I found out it is not always redirecting correctly.
E.g. **Ustilago maydis (DC.) Corda** has link https://www.gbif.org/species/148437766 and is not working 
The key-column indicates 152543131 and this is working https://www.gbif.org/species/152543131. But data source is then [Global Register of Introduced and Invasive Species - Belgium](https://www.gbif.org/dataset/6d9e952f-948c-4483-9807-575348147c7e)
The source column indicates however the [Ad hoc checklist of alien species in Belgium](https://www.gbif.org/dataset/1f3505cd-5d98-4e23-bd3b-ffe59d05d7c2) and then it has a different id 164300763 in gbif https://www.gbif.org/species/164300763

(2) The source is sometimes missing while we could construct a link using the key column.
E.g. **Melampsoridium betulinum (Pers.) Kleb.** has no link
The key-column indicates 152543152 and this is working https://www.gbif.org/species/152543152

Can I just use the id from the key-column or do you expect errors with that?

**Comment by timadriaens** [comment]
I think we can but I would like a green light from @damianooldoni or @peterdesmet

**Comment by damianooldoni** [comment]
The `key` links to the taxon as published in the [Global Register of Introduced and Invasive Species - Belgium](https://www.gbif.org/dataset/6d9e952f-948c-4483-9807-575348147c7e), here further mentioned as the _unified checklist_.
The `nubKey` is the link to the taxon in the GBIF Taxonomic Backbone.
The link in `source` should point to the taxon in the checklist used while producing the unified checklist. 
Probably I run the checklist indicator workflow just before a new version of the unified checklist came up with updated `source` info?

I don't know which is the end goal here, but I think using the `key` can be enough: the page you are directed to contains all information as published in the unified checklist.

I am done with rerunning and updating workflows for occurrence indicators and I am updating checklist indicators, so I think I can see if harvesting the unified checklist_ and creating a new version of the [indicators dataset](https://github.com/inbo/alien-species-portal/blob/mockup/alienSpecies/inst/extdata/data_input_checklist_indicators.tsv) will solve the broken links.

**Comment by damianooldoni** [comment]
It seems that the link in source in your example has been fixed automatically by rerunning the workflows and so using the most updated version of the unified checklist.

@mvarewyck: please, reopen this issue if you think there are still some errors in `source`. Or open a new one if you still struggle to understand the GBIF keys structure and so the differences among `key`, `nubKey` and `source`!
