### ISSUE TITLE
Changes v0.0.1

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#26]
We, @timadriaens, @jrhillae, @bramdhondt & myself went through the app in its v0.01 state. 
Foremost the app was recieved very well but it still needs "some" work. Besides some new features we came up with the following questions and suggestions for change:

### Taxon filter:
- [x] ENHANCEMENT: Allow taxon filtering in the searchbar instead of seperate search field
- [x] ENHANCEMENT: Remove taxonkeys from taxon
- [x] ENHANCEMENT: Add inverse option to "union list" ea "non-union list" species
- [x] ENHANCEMENT: Allow deletion from searchbar
- [x] BUG: when you select a species, for example _Lithobates catesbeianus_, the taxa table becomes empty while _Lithobates catesbeianus_ is shown for any higher level of the taxonomic backbone. 

### Taxa table:
- [x] NEW FEATURE: Add disclaimer. For now just a placeholder, w'll provide the text and url.
- [ ] QUESTION: How does the app get the data for this list now ? Is it connected to the GRIIS checklist on gbif ? Is it an option to make it so if not? If allready so, how often does the app check for changes ? 

### Origin:
- [x] BUG: Number of introduced species per year and per native continent graph is squished 

## Species information
- [x] ENHANCEMENT: Grey out or remove tabs with no data
- [ ] QUESTION: The observation maps are cube based, correct ? Does you get this data from zenodo then ? How often does it check for changes ? 

## Management
We are going to work out, provide you with datasources and example scripts for the following species:
- [x] #27
- [x] #28
- [ ] #29

**Comment by mvarewyck** [comment]
Link to translations to be completed: https://github.com/inbo/alien-species-portal/blob/mockup/alienSpecies/inst/extdata/translations.csv

**Comment by SanderDevisscher** [comment]
@mvarewyck the most recent version of https://zenodo.org/record/4299976#.Yp8q57wzZhF a.k.a. `be_alientaxa_cube.csv` can be found here on github https://github.com/trias-project/occ-cube-alien/blob/master/data/processed/be_alientaxa_cube.csv. 
The same is true for `be_alientaxa_info.csv` which can be found here https://github.com/trias-project/occ-cube-alien/blob/master/data/processed/be_alientaxa_info.csv & `be_classes_cube.csv` which can be found here https://github.com/trias-project/occ-cube-alien/blob/master/data/processed/be_classes_cube.csv

**Comment by SanderDevisscher** [comment]
Also this can help with downloading the data from zenodo for the remaining datasets: https://inbo.github.io/inborutils/reference/download_zenodo.html

**Comment by mvarewyck** [comment]
An alternative filter has been implemented for 'Taxa' to meet the requested enhancements. 
Please review & let me know if this is better than before. We can still change (formatting of) the text, ordering.
If needed, we can also implement similar filtering for 'pathways' and 'native regions'.

**Comment by mvarewyck** [comment]
Wrt the questions: All data are static (downloaded once by hand) [here](https://github.com/inbo/alien-species-portal/tree/mockup/alienSpecies/inst/extdata)
