### ISSUE TITLE
Management page Lithobates catesbeianus 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#28]
Provide datasources and example scripts for Lithobates page.

- [x] repair dataflow to gbif
- [x] provide datasource
- [x] create example script

**Comment by SanderDevisscher** [comment]
Data from 2010 till 2018 can be found here https://www.gbif.org/dataset/ea95fd9b-58dc-4e48-b51f-9380e9804607.
Data from 2018 onwards is being prepped as we speak and can be found on gbif somewhere this fall.

**Comment by SanderDevisscher** [comment]
repair status see https://github.com/inbo/sk-analyse/issues/6

**Comment by SanderDevisscher** [comment]
example code status see https://github.com/inbo/sk-analyse/issues/7

**Comment by SanderDevisscher** [comment]
@mvarewyck data voor deze pagina kan gevonden worden hier [Lithobates_catesbeianus_management_data.csv](https://github.com/inbo/sk-analyse/blob/main/interim/Lithobates_catesbeianus_management_data.csv) en het voorbeeld script staat hier [management_graphs.Rmd](https://github.com/inbo/sk-analyse/blob/main/script/management_graphs.Rmd)

**Comment by mvarewyck** [comment]
Op provincie niveau is zowel de regio Antwerpen rood als de occurrence cubes.
Moeten we een andere kleurschaal gebruiken? Zoja, suggesties?

Momenteel zijn 
* de regio's: Green-Yellow-Red
* occurrence cubes: red

![Screenshot from 2022-12-13 12-14-08](https://user-images.githubusercontent.com/22143743/207303309-41f933a3-1fe5-4b0f-8cba-99bca1e447a9.png)

**Comment by mvarewyck** [comment]
Beter voorbeeld

![Screenshot from 2022-12-13 12-18-30](https://user-images.githubusercontent.com/22143743/207304195-bc615a2e-bc3a-4b1f-8313-1ea31dddc035.png)

**Comment by SanderDevisscher** [comment]
Eventueel dezelfde schaal als op faunabeheer.inbo.be (shades of orange)

Vraagje, is de data op voorbeeld al gefilterd op het jaar ? ifso, dan klopt er iets niet in 2018 werden er zeker geen 10000+ stierkikkers meer gevangen in Hoogstraten.

**Comment by mvarewyck** [comment]
> Vraagje, is de data op voorbeeld al gefilterd op het jaar ? ifso, dan klopt er iets niet in 2018 werden er zeker geen 10000+ stierkikkers meer gevangen in Hoogstraten.

Normaal wel, ik moet bekijken dan wat er fout loopt in het script.

**Comment by mvarewyck** [comment]
> > Vraagje, is de data op voorbeeld al gefilterd op het jaar ? ifso, dan klopt er iets niet in 2018 werden er zeker geen 10000+ stierkikkers meer gevangen in Hoogstraten.
> 
> Normaal wel, ik moet bekijken dan wat er fout loopt in het script.

De filtering gebeurde na de sommatie, fixed. @SanderDevisscher Let wel op, in jouw script is dit nog niet gecorrigeerd https://github.com/inbo/sk-analyse/blob/main/script/management_graphs.Rmd#L143-L147

Deze zou wel correct moeten zijn:
![Screenshot from 2022-12-15 14-04-26](https://user-images.githubusercontent.com/22143743/207866215-f21b1eb5-f59b-4de4-82d7-85c4569f95f6.png)


Willen jullie ook barplot voor cpue? Momenteel enkel voor sum & cumsum, al dan niet per lifestage group.

![Screenshot from 2022-12-15 14-05-43](https://user-images.githubusercontent.com/22143743/207866455-03872940-2047-4613-b772-8df1a1a69a43.png)

**Comment by SanderDevisscher** [comment]
@mvarewyck dat ziet er al beter uit !
correct me if I'm wrong maar het feit dat de filter voor of na de sommatie staat maakt toch niks uit als je de som per jaar berekend dmv `dplyr::group_by(year)`. 

> Willen jullie ook barplot voor cpue? Momenteel enkel voor sum & cumsum, al dan niet per lifestage group.

ja graag!

**Comment by mvarewyck** [comment]
> correct me if I'm wrong maar het feit dat de filter voor of na de sommatie staat maakt toch niks uit als je de som per jaar berekend dmv dplyr::group_by(year).

Correct, te snel van mij. In mijn code is er geen grouping by year.

**Comment by SanderDevisscher** [comment]
oef ik begrijp R nog :-p
