### ISSUE TITLE
TRANSLATE

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#30]
Link to translations to be completed: https://github.com/inbo/alien-species-portal/blob/mockup/alienSpecies/inst/extdata/translations.csv

_Originally posted by @mvarewyck in https://github.com/inbo/alien-species-portal/issues/26#issuecomment-1265118348_

Je kan dit bestand lokaal bewerken als volgt:

1. Open github desktop
2. Selecteer de `mockup`- branch
3. fetch/pull branch
4. klik op show in explorer of klik `ctrl`+ `shift`+ `f`
5. open het bestand dmv excel
6. vertaal tekst
7. sla je wijzigingen op (`ctrl`+ `s`)
8. commit & push je wijzigingen

**Comment by b-dhondt** [comment]
@SanderDevisscher - _Done_. Let op: scheidingsteken is onbedoeld gewijzigd van komma naar puntkomma.

**Comment by mvarewyck** [comment]
Some new translations might be needed: 0d53486b24137ba22597814c7fae2f9d7450a4af

**Comment by b-dhondt** [comment]
If something is expected, please provide a clear request (of action and by whom).

**Comment by mvarewyck** [comment]
> @SanderDevisscher - _Done_. Let op: scheidingsteken is onbedoeld gewijzigd van komma naar puntkomma.

Which encoding was used to create the file? I can't read it with UTF-8, UTF-16 or Latin (all special characters are not recognized)

**Comment by b-dhondt** [comment]
As all fields needed to align well in order to perform the translations, I opened and wrote the _csv_ using Microsoft Excel. Though I had the troubles with the special characters, too. (Correcting them apparently didn't change much...)

**Comment by mvarewyck** [comment]
@bramdhondt Kan je nog eens door de [translation file](https://github.com/inbo/alien-species-portal/blob/mockup/alienSpecies/inst/extdata/translations.csv) gaan een aanvullen/wijzigen waar nodig?

**Comment by b-dhondt** [comment]
@mvarewyck -- Ik ben er grondig doorgegaan. Zie de _csv_ (gepusht).

Aangezien dit enkel werkbaar is in Excel en vanwege het risico op compatibiliteitsproblemen, zeker gezien het hoge aantal leestekens, heb ik de oorspronkelijke versie ook als backup opgeslaan (_translations_BACKUP_22-11-30-14-28_DELETE_ME.csv_) en ook de _xlsx_ behouden (_translations_v22-11-30.xlsx_).

_For the record_: de Franse vertaling van de pathways komen één op één uit een rapport van Dutrieux & Magnier (2017).

**Comment by b-dhondt** [comment]
@mvarewyck -- Ik ben ook nog eens door de Nederlandstalige _pathways_ gegaan, om die op één lijn te zetten met de Franse en Engelse versies. _translations.csv_ is aldus geüpdatet.

Daarmee denk ik met deze _issue_ klaar te zijn.

**Comment by mvarewyck** [comment]
@bramdhondt Enkel de formatting van de xlsx file is correct. Ik kan daarmee verder. In de toekomst is het dus best om de xlsx aan te passen en dan (door ons) een csv te laten aanmaken met UTF-8 coding.

**Comment by mvarewyck** [comment]
@bramdhondt Er zijn nog vertalingen bijgekomen oa. door #28 . Ik heb ze aangevuld in de csv file.

**Comment by b-dhondt** [comment]
@mvarewyck -- Vertalingen aangebracht in `translations_v22-12-20.xlsx` . Van daaruit kunt u een nieuwe _csv_ maken. De vorige versie van de _xlsx_ kunt u allicht verwijderen.

**Comment by mvarewyck** [comment]
@bramdhondt Kan je een nieuwe ronde vertalingen doen? Dit is de laatste versie https://github.com/inbo/alien-species-portal/blob/mockup/alienSpecies/inst/extdata/translations.csv

**Comment by b-dhondt** [comment]
@mvarewyck De 'laatste versie' waar je naar verwijst bevat nog niet de wijzigingen die ik in het bericht van 20 december 2022 heb doorgevoerd (`translations_v22-12-20.xlsx`, [link](https://github.com/inbo/alien-species-portal/blob/mockup/alienSpecies/inst/extdata/translations_v22-12-20.xlsx)). Zie bv. vertalingen voor de continenten, `Africa` t.e.m. `Western Europe`; soortstatus, `captive` t.e.m. `widespreadInvasive`; ...

Kunnen deze eerst worden ingewerkt, zodat duidelijker wordt waar er nog vertalingen ontbreken?

**Comment by mvarewyck** [comment]
@bramdhondt Vertalingen zijn up-to-date nu.
In de huidige file is er een extra kolom per taal voor 'description'. Hierin kan je extra tekst per figuur plaatsen (in de toekomst)

**Comment by b-dhondt** [comment]
@mvarewyck - Dag Machteld, ik heb een nieuwe versie van de _xlsx_ gepusht (`translations_v23-05-24.xlsx`). Ik denk dat ik alles heb. Controleer je even? Tussen nu en midden juli valt mijn beschikbaarheid sterk terug.

**Comment by mvarewyck** [comment]
@bramdhondt I've added some new labels which need translation. Just search for `TODO` in [this file](https://github.com/inbo/alien-species-portal/blob/sprint_v0.0.4/alienSpecies/inst/extdata/translations.csv)

**Comment by b-dhondt** [comment]
@mvarewyck - Dag Machteld, ik heb je vraag bekeken. Zie _**translations_v23-09-20_pars.xlsx**_ , die ik gepusht heb. De omweg via Excel verhindert conversiefouten aan mijn zijde, en vergemakkelijkt ook het overzicht. Excuses dat dit voor jou wel extra stappen betekent.

In de gele cellen heb ik een vertaling verzorgd. In de blauwe cellen heb ik bestaande tekst verbeterd.

Sommige lijnen lijken wel HTML-code te bevatten, met een foute uitlijning tot gevolg. Hieronder voorbeeld, uit [jouw csv](https://github.com/inbo/alien-species-portal/blob/sprint_v0.0.4/alienSpecies/inst/extdata/translations.csv). Met die lijnen weet ik niet heel goed wat aan te vatten.

![afbeelding](https://github.com/inbo/alien-species-portal/assets/78358923/d9e9a559-e76a-411f-9996-c566b96873d2)

**Comment by mvarewyck** [comment]
> Sommige lijnen lijken wel HTML-code te bevatten, met een foute uitlijning tot gevolg. Hieronder voorbeeld, uit [jouw csv](https://github.com/inbo/alien-species-portal/blob/sprint_v0.0.4/alienSpecies/inst/extdata/translations.csv). Met die lijnen weet ik niet heel goed wat aan te vatten.
> 
> ![afbeelding](https://user-images.githubusercontent.com/78358923/269286061-d9e9a559-e76a-411f-9996-c566b96873d2.png)

Dit zorgt ervoor dat bepaalde stukken op een nieuwe lijn `</br>` of in bold `<em>` worden weergegeven. De zaken tussen accolade, worden berekend in de code en vervangen. Zo zal bvb. `{{maxDate}}` vervangen worden door de maximum datum berekend obv de data. Het is dus best dat je deze stukjes **identiek** overneemt in de vertaling, anders is de formatting daar verschillend.

**Comment by mvarewyck** [comment]
> @mvarewyck - Dag Machteld, ik heb je vraag bekeken. Zie _**translations_v23-09-20_pars.xlsx**_ , die ik gepusht heb. De omweg via Excel verhindert conversiefouten aan mijn zijde, en vergemakkelijkt ook het overzicht. Excuses dat dit voor jou wel extra stappen betekent.

@bramdhondt No problem, I've transferred the translations that were clear from **translations_v23-09-20_pars.xlsx**. Any update on the special ones (HTML formatted)? We can also do it together during a quick call if that helps.

**Comment by b-dhondt** [comment]
@mvarewyck - Is de vraag nog geldig? (Zoja, dan zul je me wel even opnieuw moeten aanwijzen waar ik de tekst vindt.)

**Comment by mvarewyck** [comment]
> @mvarewyck - Is de vraag nog geldig? (Zoja, dan zul je me wel even opnieuw moeten aanwijzen waar ik de tekst vindt.)

@bramdhondt Yes, still relevant.

~The translations file is now on the S3 bucket. I don't know how familiar you are with R and whether you have access to the S3 bucket, but instructions on how to update the file with the S3 bucket are [here](https://github.com/inbo/alien-species-portal/blob/sprint_v0.0.4/README.md#update-the-translations-file)~
We can also do it together during a quick call for the HTML formatted ones.

~I've attached the latest translations file if the above is not working for you.
[translations.csv](https://github.com/inbo/alien-species-portal/files/13412358/translations.csv)~

@SanderDevisscher who will update the translations file in the future? Is it someone with access to the S3 bucket or should we keep the translations file into the git repository?

**Comment by SanderDevisscher** [comment]
@mvarewyck didn't we agree on placing the translation file here https://github.com/inbo/aspbo/blob/21-upload-files-to-uat/data/output/UAT_direct/translations.csv ? Thus allowing everyone from inbo to do translations. The fis-bot will do the uploading.

**Comment by mvarewyck** [comment]
@SanderDevisscher Sorry, I missed that one. That's indeed a good solution.

**Comment by b-dhondt** [comment]
@mvarewyck / @SanderDevisscher - Kun je me nog even verzekeren binnen welke _branch_ ik de laatste versie binnentrek / mijn aanpassingen _push_ ?

**Comment by SanderDevisscher** [comment]
@bramdhondt momenteel bestaat het translate bestandje enkel in de `21-upload-files-to-uat` - branch. Je mag hier je wijzigingen aan toevoegen. Tenzij het over aanzienlijke aanpassingen gaat, dan zou ik wachten tot na de merge van https://github.com/inbo/aspbo/pull/25 en daarna een nieuwe branch openen en PR'en met de `uat` - branch.

**Comment by b-dhondt** [comment]
@SanderDevisscher @fleurpet - Update van translations.csv gepusht naar branch 21 (_aspbo_-repo). Alle velden met "TODO" zijn opgelost.
