### ISSUE TITLE
Provide images for Tiles

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#31]
- [ ] species
- [ ] indicators
- [ ] early warning

**Comment by b-dhondt** [comment]
@SanderDevisscher - Kun je iets specifieker zijn wat verwacht wordt (van mij)? Eén aantrekkelijk fotootje voor elk van de drie genoemde zaken? Vormelijke vereisten?

**Comment by SanderDevisscher** [comment]
@bramdhondt wat ik van jou verwacht is dat je voorstellen aandraagt voor de 3 tegels. De voorstellen van anderen bekijkt en beoordeeld. 

@mvarewyck zijn er formaat (letterlijk alsook bestandformaat) beperkingen voor deze tegels ?

**Comment by SanderDevisscher** [comment]
Oja liefst foto's die gratis te gebruiken zijn (mits vermelding fotograaf)

**Comment by mvarewyck** [comment]
Neen, geen vereisten. De tegels zijn redelijk klein van formaat, kan zowel png als jpg. 
Momenteel tonen we [deze](https://github.com/inbo/alien-species-portal/blob/mockup/alienSpecies/inst/app/www/example.jpg)
Je mag de nieuwe bestanden in dezelfde map plaatsen

**Comment by b-dhondt** [comment]
Ik heb wat eigen foto's toegevoegd (de beste garantie wat gebruiksrechten betreft), maar valt eigenlijk wel tegen (weinig kwalitatieve foto's). Ze steken in de map (één voorstel per item; extraatjes in mapje). Zie https://github.com/inbo/alien-species-portal/tree/mockup/alienSpecies/inst/app/www .

Geef gerust jullie eerlijke mening of dit de lat haalt voor de huidige fase. Zoniet, wordt het even zoeken in het gratis aanbod (bv. wikimedia).

**Comment by timadriaens** [comment]
Aangezien het wel belangrijk is dat het er wat uitziet, dacht ik voor species aan een soortje, voor indicators aan een grafiekje, en voor early warning aan een prentje van een hand met een smartphone die aan het recorden is.

De management tab ontbreekt nog (daaronder zouden we de eerste twee trials met vespa en muntjak steken dacht ik @SanderDevisscher?) maar daar zou dan een prentje mogen komen van iemand die aan het beheren is?

Wat licenties betreft, we hebben met INBO een overeenkomst met vildaphoto, en verder voor moeilijke soorten is er altijd iNaturalist (cc0 of cc-by).

**Comment by b-dhondt** [comment]
Ik heb https://vildaphoto.net/ even doorgenomen, om daar geschikte foto's te zoeken, in de categorieën _species_, _early warning_ en _management_ (voor _indicators_ lijkt een grafiekje geschikter).

Ik heb per categorie max. 5 suggesties toegevoegd onder **.\alienSpecies\inst\app\www\Foto's** . Ik heb per categorie ook mijn voorkeur kenbaar gemaakt (prefix 'VOORKEUR').

Indien hiervoor gekozen, zijn kwalitatievere versies nog aan te kopen.

**Comment by b-dhondt** [comment]
Ik heb onder dezelfde map ook een grafiekje toegevoegd, ter invulling van _indicators_. Snel-snel o.b.v. quasi-willekeurige data. Dat kunnen we natuurlijk zelf maken en nog fine-tunen...
