### ISSUE TITLE
Trias package >= 2.0.3

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#32]
**Describe the bug**
When building the app using docker I get the following error:
 ```
> [22/23] RUN R -q -e "roxygen2::roxygenize('alienSpecies'); install.packages(pkgbuild::build('alienSpecies'), repos = NULL, dependencies = FALSE)":
#26 0.649 > roxygen2::roxygenize('alienSpecies'); install.packages(pkgbuild::build('alienSpecies'), repos = NULL, dependencies = FALSE)
#26 1.351 ℹ Loading alienSpecies
#26 3.672 Error in load_imports(path) : The package `trias` (>= 2.0.3) is required.
#26 3.672 Calls: <Anonymous> ... load_imports -> deps_check_installed -> check_installed
#26 3.672 Execution halted
```

**To Reproduce**
1. Go to `Mockup` - branch
2. Fetch branch
3. run `devtools::build("alienSpecies")`
5. in powershell run `docker build -t openanalytics/r-base .`
6. See error

**Expected behavior**
succesfull build in docker

**Additional context**
Building in R works like it should

**Comment by SanderDevisscher** [comment]
See readme in mockup branch

**Comment by SanderDevisscher** [comment]
The readme in the mockup branch is outdated since the `packamon` package is no longer available for R. Using `devtools::build()` instead yields the same error.

**Comment by mvarewyck** [comment]
Your steps for building the docker image are correct. You don't need the R package `packamon` for that. 

Normally `trias` should get installed from github: https://github.com/inbo/alien-species-portal/blob/mockup/Dockerfile#L158
I guess something went wrong a bit earlier in the docker build.

(I'm running the docker build right now to see what goes wrong, but it takes a while)

**Comment by mvarewyck** [comment]
@SanderDevisscher Can you try again with 981ddb8f22cb44173817d3888b673910c29b8f0b

**Comment by SanderDevisscher** [comment]
Building in docker seems to get past point of previous error

**Comment by SanderDevisscher** [comment]
Builden in docker was succesfull

**Comment by SanderDevisscher** [comment]
It also runs in docker
