### ISSUE TITLE
Create GAMs per region

### ISSUE THREAD

**Issue by timadriaens** [inbo/alien-species-portal#34]
For emerging status and the graphs with the time series we have filters set on  region (the same way people can select on region in the checklist). In principle there is no problem to assign km squares to regions, and I think @damianooldoni already tailored for this.

So we would like to be able to have the GAMs for emergin species selection for Belgium, but also refined for the different regions (FLA, WAL, BRX).

**Comment by mvarewyck** [comment]
@timadriaens @SanderDevisscher Do you also want the option to select more than 1 region (e.g. FLA + WAL) or will it always be a single region?

**Comment by timadriaens** [comment]
Single region is fine (on top of entire Belgium)
