### ISSUE TITLE
upload new communities & provinces geojson

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#47]
Add .geojsons of communities & provinces

with `gewest` column

**Comment by mvarewyck** [comment]
Please also include the communities & provinces of Wallonia & Brussels
See [here](https://github.com/inbo/alien-species-portal/issues/37#issuecomment-1489932935)

**Comment by SanderDevisscher** [comment]
@mvarewyck I've uploaded the requested files, can you confirm ?

**Comment by mvarewyck** [comment]
@SanderDevisscher Files have all necessary information. However, not all region names match with those in  https://github.com/inbo/alien-species-portal/blob/mockup/alienSpecies/inst/extdata/management/Lithobates_catesbeianus.csv

Can you change in communes.geojson 'NAAM' column to be lowercase format: e.g. Herk-De-Stad ipv HERK-DE-STAD
