### ISSUE TITLE
CBD, level 2 trends

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#48]
**Is your feature request related to a problem? Please describe.**
Currently only the trend graph for level 1 exists. This should be expanded to also include the level 2 pathway trends.

**Describe the solution you'd like**
New graph similar to `Introduced species per pathway (CBD, level 1) - trends` for the level 2 pathways.

**Additional context**
Should be placed below `Introduced species per pathway (CBD, level 2)`. I should also come with the same disclaimer

**Comment by timadriaens** [comment]
yep, level 2 is an important one with the highest degree of detail that we have
