### ISSUE TITLE
Management page Ondatra zibethicus

### ISSUE THREAD

**Issue by EmmaCartuyvels1** [inbo/alien-species-portal#50]
Muskrat management data (catches made) can be found in datasets published on GBIF with the following dataset keys "ddd51fa5-97ce-48ff-9a58-a09d7e76b103", "b7ee2a4d-8e10-410f-a951-a7f032678ffe", "95b0e787-8508-4247-9e48-18b45fc7d12e", "3634aee3-41d5-4aa2-8cb5-875859f62a3a", "69351197-880d-4100-8e69-e80babf3fdd7".

However some data is still missing:
- [ ] West Flemish data from 2019 onward
- [ ] Non-RATO data from East-Flanders from 2019 onward

Ideally this data will be published on GBIF as well, this process is underway: https://github.com/inbo/mica-occurrences

IMPORTANT: these datasets contain both catches and observations and only catches should be considered for analyses. It is unclear if this distinction can be made based on the GBIF export.

Analyses using these data can be found here:
https://github.com/inbo/muskusratten/blob/master/Scripts/AnaGBIF.R

This code visualises the catches over the years, indicating each province in a different colour:
```
## Evolutie vangsten
catches_year <- d %>%
  filter(stateProvince %in% c("West Flanders", "East Flanders", 
                              "Flemish Brabant", "Antwerp", "Limburg")) %>%
  filter(year < 2023) %>% 
  group_by(year, stateProvince) %>%
  summarise(catches = sum(individualCount, na.rm = TRUE))


ggplot(catches_year, 
       aes(x = year, y = catches, fill = stateProvince)) +
  geom_bar(position = "stack", 
           stat = "identity") +
  facet_zoom(xy = year > 2008, 
             horizontal = FALSE, 
             zoom.size = 1.5,
             zoom.data = ifelse(year>2008, NA, FALSE)) +
  labs(x = "Jaar", y = "Vangsten") +
  scale_fill_discrete(name = "Provincie", labels = c("Antwerpen",
                                                     "Oost-Vlaanderen", 
                                                     "Vlaams-Brabant", 
                                                     "Limburg", 
                                                     "West-Vlaanderen"))
```

This code shows catches made per muncipality for a given year:
```
catches_gem <- d %>%
  group_by(year, gemeente, .drop=FALSE) %>%
  summarise(catches = sum(individualCount, na.rm = TRUE)) %>% 
  st_drop_geometry()


VL_Gem <- gem %>% 
  filter(LanguageSt %in% c(1, 5)) %>% 
  select(gemeente = NameDut) %>% 
  mutate(year = 2022,
         catches = 0) %>% 
  st_drop_geometry()


catches_gem_2022 <- catches_gem %>% 
  filter(year == 2022) %>%
  ungroup() %>% 
  add_row(VL_Gem) %>% 
  group_by(year, gemeente) %>% 
  summarise(catches = sum(catches, na.rm = TRUE))


data <- gem %>% 
  left_join(catches_gem_2022, 
            by = c("Gemeente" = "gemeente"))


pal <- colorBin(palette = rev(heat.colors(11)), 
                bins = c(-Inf,0.0001,5,10,25,50,100,+Inf),
                na.color="#cecece")


leaflet(data, options = leafletOptions(minZoom = 7, maxZoom = 10)) %>%
  addTiles() %>% 
  addLegend(title = paste("Gevangen muskusratten 2022"),
            pal = pal, values = ~catches, 
            position = "bottomleft") %>%
  addPolygons(color = ~ pal(catches), 
              stroke = FALSE, smoothFactor = 0.2, fillOpacity = 0.85,
              popup=sprintf("<strong>%s</strong><br>%s",
                            data$Gemeente, data$catches)) %>%
  addPolylines(weight = 1.5, color = "white") %>%
  setView(4.2813167, 50.76, zoom = 8) %>% 
  addPolygons(data = provincies, group = "Provincies", fill = NA,
              color = "forestgreen", weight = 2)
```
This code shows the evalution of catches per border area:
```
Wal <- c("Voeren", "Riemst", "Mesen", "Ieper", "Zonnebeke", "Wervik", "Menen", 
         "Kortrijk", "Spierre-Helkijn", "Avelgem", "Kluisbergen", "Ronse", 
         "Maarkedal", "Brakel", "Geraardsbergen", "Bever", "Herne", "Pepingen", 
         "Halle", "Beersel", "Sint-Genesius-Rode", "Hoeilaart", "Overijse", 
         "Huldenberg", "Oud-Heverlee", "Bierbeek", "Boutersem", "Hoegaarden", 
         "Tienen", "Landen", "Gingelom", "Heers", "Tongeren", "Herstappe")
Fran <- c("De Panne", "Veurne", "Alveringem", "Poperinge", "Heuvelland")
Ned <- c("Lanaken", "Maasmechelen", "Dilsen-Stokkem", "Maaseik", "Kinrooi", 
         "Bree", "Bocholt", "Hamont-Achel", "Neerpelt", "Lommel", "Mol", 
         "Arendonk", "Ravels", "Turnhout", "Baarle-Hertog", "Merksplas", 
         "Hoogstraten", "Wuustwezel", "Kalmthout", "Essen", "Kapellen", 
         "Stabroek", "Antwerpen", "Beveren", "Sint-Gillis-Waas", "Stekene", 
         "Moerbeke", "Wachtebeke","Zelzate", "Assenede", "Sint-Laureins", 
         "Maldegem", "Damme", "Knokke-Heist")


stap1 <- catches_gem %>%  
  mutate(Grens =  ifelse(gemeente %in% Wal, "Wal", "Nee")) %>%
  mutate(Grens =  ifelse(gemeente %in% Fran, "Fran", Grens)) %>%
  mutate(Grens =  ifelse(gemeente %in% Ned, "Ned", Grens))


stap1 %>% 
  filter(year > 2009 & year < 2023) %>% 
  group_by(year, Grens) %>% 
  summarise(catches = sum(catches, na.rm = TRUE)) %>% 
  ggplot(aes(x = year, y = catches)) +
  geom_point(aes(color = Grens)) +
  geom_line(aes(color = Grens)) +
  scale_x_continuous(breaks = 2010:2022) +
  labs(x = "Jaar", y = "Vangsten") +
  scale_color_discrete(name = "Gemeente grenst aan:", labels = c("Frankrijk",
                                                     "Nederland", 
                                                     "Geen grensgemeente", 
                                                     "Wallonië"))
```
This code visualises the change in catches compared to the previous year per muncipality:
```
VL_Gem_ext <- expand.grid(VL_Gem$gemeente, c(1991:2022)) %>% 
  mutate(catches = 0) %>% 
  rename(gemeente = Var1,
         year = Var2)


catches_gem_full <- catches_gem %>%
  ungroup() %>% 
  add_row(VL_Gem_ext) %>% 
  group_by(year, gemeente) %>% 
  summarise(catches = sum(catches, na.rm = TRUE)) %>% 
  ungroup() %>% 
  arrange(gemeente, year) %>% 
  mutate(prev_catch = lag(catches)) %>% 
  mutate(change = catches - prev_catch)




data <- catches_gem_full %>%
  filter(year == 2022) %>% 
  left_join(gem, 
            by = c("gemeente" = "Gemeente"))


data <- st_as_sf(data)


pal <- colorBin(palette = "PiYG", 
                bins = c(-Inf,-100,-50,-25,-10,-5,0,5,10,25,50,100,+Inf),
                na.color="#cecece",
                reverse = TRUE)


leaflet(data, options = leafletOptions(minZoom = 7, maxZoom = 10)) %>%
  addTiles() %>% 
  addLegend(title = paste("Toename / afname aantal vangsten"),
            pal = pal, values = ~change, 
            position = "bottomleft") %>%
  addPolygons(color = ~ pal(change), 
              stroke = FALSE, smoothFactor = 0.2, fillOpacity = 0.85,
              popup=sprintf("<strong>%s</strong><br>%s",
                            data$gemeente, data$change)) %>%
  addPolylines(weight = 1.5, color = "white") %>%
  setView(4.2813167, 50.76, zoom = 8) %>% 
  addPolygons(data = provincies, group = "Provincies", fill = NA,
              color = "forestgreen", weight = 2)
```

**Comment by timadriaens** [comment]
it would be great to have these management results graphs and maps on the dashboard!

**Comment by SanderDevisscher** [comment]
@mvarewyck I'll write a script to extract the neccessary data from gbif and provide you with some cleaned datasets to use.

**Comment by SanderDevisscher** [comment]
@mvarewyck like I see it these 2 visualisations are similar to those we allready have:

- "This code visualises the catches over the years, indicating each province in a different colour:" == region graph at province scale. But should be added for other scales as well (ea Gewest, Provinces & Communities) 
- "This code shows catches made per muncipality for a given year:" == default management map on region scale also including other scale levels (ea Gewest, Provinces & Communities) 

While the other 2 are new. 
- "This code shows the evalution of catches per border area:" I see some options here, @mvarewyck can you indicate feasability/time cost:
       - Is it possible to add the border regions as municipality scale options. Ifso should I add them to the data ?
       - or we could consider this as a separate graph
- "This code visualises the change in catches compared to the previous year per muncipality:"
       - @EmmaCartuyvels1 can you indicate the necessity of this visualisation? Or is it sufficient to have a map with time slider? 
       - @mvarewyck how much time would it cost to add a map indicating change when we provide a data frame with province, niscode & change as columns ?

**Comment by EmmaCartuyvels1** [comment]
"This code visualises the change in catches compared to the previous year per muncipality:"
I do think that this gives an instant idea of which areas are (becoming) problem areas and will be easier to interpret by field managers than having to compare the different years by themselves.

**Comment by mvarewyck** [comment]
> * "This code shows the evalution of catches per border area:" I see some options here, @mvarewyck can you indicate feasability/time cost:
>   - Is it possible to add the border regions as municipality scale options. Ifso should I add them to the data ?

In the app I would add an extra option 'border municipalities' for Region level. In the data I would prefer to have an extra column 'isBorderMunicipality' with value TRUE/FALSE, besides the 'municipality' column. 
(1) Preselect all border regions and _hide the other municipalities_ in the map (gray?). To have this implemented, I would count 1 day.
(2) If we don't need to _hide the other municipalities_ but just preselect the border regions and showing these in the 'Regions' input field, we can mostly re-use the code of 'municipalities' option, and I would count 0.5 day.
![Screenshot from 2023-09-28 12-13-00](https://github.com/inbo/alien-species-portal/assets/22143743/78717f39-26d8-4110-8b21-a6651fbeaaca)

>   - or we could consider this as a separate graph

Same cost as above. Less efficient coding-wise because we copy-paste code.

> * "This code visualises the change in catches compared to the previous year per muncipality:"
>   - @mvarewyck how much time would it cost to add a map indicating change when we provide a data frame with province, niscode & change as columns ?

I would count 0.5 day.

**Comment by mvarewyck** [comment]
> "This code shows the evalution of catches per border area:" I see some options here, @mvarewyck can you indicate feasability/time cost:
> * Is it possible to add the border regions as municipality scale options. Ifso should I add them to the data ?

We drop this plot


> "This code visualises the change in catches compared to the previous year per muncipality:"
> * @mvarewyck how much time would it cost to add a map indicating change when we provide a data frame with province, niscode & change as columns ?

We keep this plot. Also include it for the other management pages if relevant. Include the unit 'Difference with previous year' as an option besides absolute count

**Comment by EmmaCartuyvels1** [comment]
@mvarewyck here is some sample data
[muskrat_sample.csv](https://github.com/inbo/alien-species-portal/files/12763093/muskrat_sample.csv)

**Comment by mvarewyck** [comment]
@EmmaCartuyvels1 Thanks. Some remarks on the current data format

* The first column are row names, which is best removed. We don't have it for the other management data files and trying to read all files with the same code.
* The file is comma-separated, so the geometry column is not read correctly as it contains coordinates e.g. c(3.95537,	 50.80789). You already have `decimalLatitude` and `decimalLongitude` so I suggest you drop the `geometry` column.
* I have replaced stateProvince -> `provincie` and gemeente -> `NAAM` in accordance with the other datasets

I've done this manually for now, but good to keep in mind with future data updates.

**Comment by mvarewyck** [comment]
I've created a draft version of the mgt page similar to the one for Lithobates catesbeianus.

![Screenshot from 2023-10-16 15-05-26](https://github.com/inbo/alien-species-portal/assets/22143743/5e9d5d94-4e72-4272-b0f8-bd9309b82a52)
![Screenshot from 2023-10-16 15-05-50](https://github.com/inbo/alien-species-portal/assets/22143743/bac2b74b-d6ed-4a4e-bf80-8a8034c7a5f1)
![Screenshot from 2023-10-16 15-11-14](https://github.com/inbo/alien-species-portal/assets/22143743/df3f409c-b89e-499b-baf8-8eb33600c006)

@EmmaCartuyvels1 @SanderDevisscher Some questions/remarks

* There are a lot of observations with NA for individualCount, for all years before 2021. Should we (a) exclude the rows with NA values then the barplot starts at 2021. Or (b) set the value to 0 then the barplot starts at 2016 with 0 counts until 2021. (Currently (a) is implemented)
* We don't have 'cpue' unit choice as we don't have information on n_fuiken.
* Provinces are named in English, preferably in Dutch, like for the other datasets.
* Province is often missing, while exact coordinates are known. Can it be completed or is there a reason for being missing?
* Variable (column) 'Gewest' is missing to display the results per gewest.
* Which cutoff points to use? Counts are much smaller than for  Lithobates catesbeianus. Currently all counts fall in the first interval.
* For Lithobates catesbeianus we have a nice overlap between cube occurrence and captures: whenever there's a red square observation the polygon is colored. For Ondatra zibethicus this is not the case. Is this to be expected?

![Screenshot from 2023-10-16 15-00-57](https://github.com/inbo/alien-species-portal/assets/22143743/d957596a-3309-40e6-87ec-b6ab18a00a08)


TODO by me
* Fix the decimals on year axis
* Create 'difference with previous year' map

**Comment by EmmaCartuyvels1** [comment]
> * There are a lot of observations with NA for individualCount, for all years before 2021. Should we (a) exclude the rows with NA values then the barplot starts at 2021. Or (b) set the value to 0 then the barplot starts at 2016 with 0 counts until 2021. (Currently (a) is implemented)

If we are only using the GBIF data there will be some NA's that aren't zeros (eg Limburg, Antwerp and Flemish Brabant will be 0 but for other provinces it might also be a case of missing data). However, there should be data going back to 1991.

**Comment by EmmaCartuyvels1** [comment]
> * We don't have 'cpue' unit choice as we don't have information on n_fuiken.

Some of the raw data does have this info, but I don't think it's published to GBIF. If you want to include this you should ask @LienReyserhove or @DimEvil.

**Comment by EmmaCartuyvels1** [comment]
> * For Lithobates catesbeianus we have a nice overlap between cube occurrence and captures: whenever there's a red square observation the polygon is colored. For Ondatra zibethicus this is not the case. Is this to be expected?

I'm assuming the cubes come from waarnemingen? Then it would be expected since muskrats are not often active during the day and trappers don't record them in waarnemingen.

**Comment by SanderDevisscher** [comment]
> * Provinces are named in English, preferably in Dutch, like for the other datasets.
> * Province is often missing, while exact coordinates are known. Can it be completed or is there a reason for being missing?
> * Variable (column) 'Gewest' is missing to display the results per gewest.

I'm working on this, @EmmaCartuyvels1 used different shapes for provinces/communes. Once these changes are done I'll upload the new files (see https://github.com/inbo/aspbo/pull/22).

**Comment by SanderDevisscher** [comment]
> > * For Lithobates catesbeianus we have a nice overlap between cube occurrence and captures: whenever there's a red square observation the polygon is colored. For Ondatra zibethicus this is not the case. Is this to be expected?
> 
> I'm assuming the cubes come from waarnemingen? Then it would be expected since muskrats are not often active during the day and trappers don't record them in waarnemingen.

The cubes are a gbif product (using a Trias workflow, [more info](https://github.com/trias-project/occ-cube-alien)) the current cube is outdated (2022-03-09) and given the fact a lot of (historical & recent) muskrat management data (often the only observation source) have been uploaded to gbif more recently (after 04-2022, see https://github.com/riparias/vmm-rattenapp-occurrences) one would expect a mismatch. This will, hopefully, be fixed with an updated cube (see https://github.com/inbo/aspbo/issues/18).

**Comment by SanderDevisscher** [comment]
@mvarewyck which columns do you need to create the graphs/maps ? I think some of the columns currently in the dataset are not needed persé to create the graphs/maps.

**Comment by mvarewyck** [comment]
> @mvarewyck which columns do you need to create the graphs/maps ? I think some of the columns currently in the dataset are not needed persé to create the graphs/maps.

Indeed, many columns are redundant. I kept these:

![Screenshot from 2023-10-16 21-23-13](https://github.com/inbo/alien-species-portal/assets/22143743/36af41a6-3bed-4fa0-aa93-cdac55bae532)


Optional: `gbifID` is good for tracking issues with the data. `decimalLatitude` and `decimalLongitude` currently not used in the maps, but can be used to complete missing values on the location.

**Comment by mvarewyck** [comment]
Examples of plotting the difference with previous year

Ondatra zibethicus in 2022 per gemeente

![Ondatra zibethicus_2022_management](https://github.com/inbo/alien-species-portal/assets/22143743/10ca4589-1a02-413f-a09f-14fc96ea75a4)

Lithobates catesbeianus in 2018 per province

![Lithobates catesbeianus_2018_management](https://github.com/inbo/alien-species-portal/assets/22143743/feb987c2-8b2d-4386-9625-caf797966ad7)

Lithobates catesbeianus trend plot per gemeente

![Screenshot from 2023-10-17 12-00-17](https://github.com/inbo/alien-species-portal/assets/22143743/e27563ec-8cfe-4630-9c3d-5ab301e7fa64)


**Questions/Remarks**

* We now can have negative values in the legend. I changed the separator from `-` into `,`. Should we add brackets, like in a mathematical formulation?
* The 'Yellow-Orange-Brown' color palette is not useful for differences. I changed it to 'Red-Orange-Green', but this conflicts with 'Occurrence' in red (see plot above).

Alternative color palettes:

![029-r-color-palettes-rcolorbrewer-palettes-1](https://github.com/inbo/alien-species-portal/assets/22143743/01fecd94-e21e-4021-a11c-7e0c0263bc0c)

**Comment by EmmaCartuyvels1** [comment]
> * The 'Yellow-Orange-Brown' color palette is not useful for differences. I changed it to 'Red-Orange-Green', but this conflicts with 'Occurrence' in red (see plot above).

I do like the 'Red-Orange-Green' since red = bad = more animals than last year and the reverse for green. Can we change the occurences squares to blue or this not an option?

**Comment by mvarewyck** [comment]
> > * The 'Yellow-Orange-Brown' color palette is not useful for differences. I changed it to 'Red-Orange-Green', but this conflicts with 'Occurrence' in red (see plot above).
> 
> I do like the 'Red-Orange-Green' since red = bad = more animals than last year and the reverse for green. Can we change the occurences squares to blue or this not an option?

It was decided to have red squares [here](https://github.com/inbo/alien-species-portal/issues/58) in contrast with the background map.
We can change to any color, example 'blue' below.

![Screenshot from 2023-10-17 13-59-02](https://github.com/inbo/alien-species-portal/assets/22143743/db6c6fd1-228d-4dc5-a2bd-7efa4887fb18)

**Comment by Fhuysent** [comment]
For me, blue is OK!
