### ISSUE TITLE
Options Feedback form

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#54]
@mvarewyck wat is er mogelijk om gebruikers feedback aan ons te laten bezorgen ? een mail verzenden naar faunabeheer@inbo.be lijkt me niet uitzonderlijk moeilijk. Maar bestaat er ook de mogelijkheid om bvb een feedback formulier toe te voegen ?

**Comment by mvarewyck** [comment]
(1) 'Contact' link rechts bovenaan op de webpagina zoals voor faunabeheer.inbo.be is eenvoudigst. Deze opent dan een venster _in de gebruiker zijn standaard mailaccount_ aan faunabeheer@inbo.be
We kunnen hier eventueel al een template voorzien in het bericht: bvb. Beschrijf kort het probleem (welke parameters gekozen werden), welke webbrowser er gebruikt is en dat ze screenshots toevoegen indien mogelijk.

(2) We kunnen via de contact link ook een formulier laten openen in de web applicatie in een apart venster. Daar zal de gebruiker dan gegevens moeten invullen zoals zijn email adres etc. Deze mail wordt dan verstuurd _vanuit de web applicatie_ naar faunabeheer@inbo.be (en dus vanuit R). Dit is omslachtiger, omdat we hiervoor extra R package [mailR](https://cran.r-project.org/web/packages/mailR/index.html) moeten installeren met system dependency Java, waar ik al wat moeilijkheden mee heb ondervonden. 

Mijn voorkeur gaat dus naar optie 1

**Comment by SanderDevisscher** [comment]
option 1 it will be

**Comment by mvarewyck** [comment]
The 'Contact' link is there.
Do you want a specific pre-filled text in the email or title? Language dependent?

**Comment by SanderDevisscher** [comment]
How hard is it to pre fill some info about the browser and operating system as described in the listing of the options? 

I would add the same fields as [bug_report.md](https://github.com/inbo/alien-species-portal/blob/uat/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by mvarewyck** [comment]
FYI: Turned out to be easy using https://email-link-builder.netlify.app/
