### ISSUE TITLE
Inbotheme gets installed twice 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#55]
I'm trying to run alienSpecies::createTimeseries() using github actions but I get the following error while installing the app:
```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘INBOtheme’ 0.6.0 is being loaded, but <= 0.5.9 is required
```
Looking into the dockerfile I see the following:
On this line the most current version (currently 6.0.0) gets installed 
https://github.com/inbo/alien-species-portal/blob/dbda31562fbc24d3ccb1b45bde96c8df7eab3c82/Dockerfile#L199

while on this line version 0.5.9 get installed 
https://github.com/inbo/alien-species-portal/blob/dbda31562fbc24d3ccb1b45bde96c8df7eab3c82/Dockerfile#L203

I think this causes an issue

**Comment by mvarewyck** [comment]
Normally, installing an R package twice in docker shouldn't be problematic.

The current dockerfile is generated automatically, so first installing the latest available version of all R package dependencies. However, later we overwrite INBOtheme manually with specific version as was requested by you (old color palette).
