### ISSUE TITLE
Create link to obs pages

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#59]
Link to wnm.be and/or inaturalist

**Comment by SanderDevisscher** [comment]
a link to https://waarnemingen.be/fieldwork/observations/create/? and/or https://www.inaturalist.org/observations/upload should be added to channel people to report missing data. 

@timadriaens I suggest we place it at the top of the species page, what do you think?

**Comment by mvarewyck** [comment]
As discussed during meeting 29/2: Provide a 'floating' button at the bottom of the page, like currently the one for 'Create Report' which opens a popup window with the links above to report missing data

**Comment by mvarewyck** [comment]
I have included a button at the bottom, visible on both the 'Global indicators' and 'Species information' page.
The 'Contact' link at the top is removed.

![Screenshot from 2024-04-29 12-30-15](https://github.com/inbo/alien-species-portal/assets/22143743/da1abcec-bf12-410d-91e4-7b6a43b11e38)

It includes 2 options:
* Report missing data
* Report issue with the application

![Screenshot from 2024-04-29 12-34-40](https://github.com/inbo/alien-species-portal/assets/22143743/daa578b4-0062-4c4c-8698-73b03d34e056)

Is this fine?
