### ISSUE TITLE
Improve the vespa management page

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#63]
### Suggestions for improvement
- Management of Vespa velutina (2017 - 2023)
    - [x] in popup drop total
    - [ ] in line graph below split lines for individuals & nests (or if to complex only nests)
- Active hotbeds
    - [x] drop managed nests
    - [x] chance untreated nests color to black
 - All observations
    - [x] rename to All observations current year
    - [x] add NestType & Management status to popup
    - [ ] add data lag disclaimer

_Originally posted by @SanderDevisscher in https://github.com/inbo/alien-species-portal/issues/27#issuecomment-1808152139_

**Comment by mvarewyck** [comment]
> in line graph below split lines for individuals & nests (or if to complex only nests)

Example below: Different linetype for nest and individual (all provinces)
@SanderDevisscher Do you want this or remove the individual?

![Screenshot from 2024-01-30 13-04-24](https://github.com/inbo/alien-species-portal/assets/22143743/086f7b09-1d8a-49cf-a1f8-be6b2b233bbc)

**Comment by mvarewyck** [comment]
Note: The blur in active hotbeds is based on the **individual** observations only (not **untreated nests**), see [here](https://github.com/inbo/alien-species-portal/blob/uat/alienSpecies/inst/app/serverFiles/serverSpecies.R#L281). This is not explicit from the text above the graph:

> This map illustrates where Asian hornet has been sighted, but where no nest has yet been successfully managed. Vespa watchers may conduct investigations at these locations. Observations are retained if they are located further than 2km from a successfully managed nest and/or are reported after a successful management action. The more intense red, the more notifications there are in close proximity to each other. Missing nests can always be reported at [vespawatch.be](https://vespawatch.be/).

@SanderDevisscher So, I would either update the code or the text.

**Comment by mvarewyck** [comment]
> * add NestType & Management status to popup

@SanderDevisscher This info is missing for the nests coming from (iNaturalist/Natuurpunt) this data source: `"#punten laag van gbif resultaat van './preprocessing/get_data_from_gbif.Rmd'
#bevat zowel individuen als nesten"`

![Screenshot from 2024-01-31 10-45-28](https://github.com/inbo/alien-species-portal/assets/22143743/df27af67-7583-4ee9-85eb-93f77be25bd7)
![Screenshot from 2024-01-31 10-45-17](https://github.com/inbo/alien-species-portal/assets/22143743/1e3fd2ef-48c3-4144-b025-08ee6bbf1bba)

**Comment by SanderDevisscher** [comment]
> > * add NestType & Management status to popup
> 
> @SanderDevisscher This info is missing for the nests coming from (iNaturalist/Natuurpunt) this data source: `"#punten laag van gbif resultaat van './preprocessing/get_data_from_gbif.Rmd' #bevat zowel individuen als nesten"`
> 
> ![Screenshot from 2024-01-31 10-45-28](https://private-user-images.githubusercontent.com/22143743/301121412-df27af67-7583-4ee9-85eb-93f77be25bd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYzMjksIm5iZiI6MTcwNjY5NjAyOSwicGF0aCI6Ii8yMjE0Mzc0My8zMDExMjE0MTItZGYyN2FmNjctNzU4My00ZWU5LTg1ZWItOTNmNzdiZTI1YmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOWQ0MWE3OThmMjU0ODRjMDllOTZmODFiNWFhNWY4ZjZjZWI0MWJiNzMxOTJlNzBmNGM2OWI2N2E3YjRhZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.peUBWTm9fu9FnNX4guaMeflxpwPLXLMJ4vnDHqyCRjU) ![Screenshot from 2024-01-31 10-45-17](https://private-user-images.githubusercontent.com/22143743/301121430-1e3fd2ef-48c3-4144-b025-08ee6bbf1bba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYzMjksIm5iZiI6MTcwNjY5NjAyOSwicGF0aCI6Ii8yMjE0Mzc0My8zMDExMjE0MzAtMWUzZmQyZWYtNDhjMy00MTQ0LWIwMjUtMDhlZTZiYmYxYmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1N2I1MzVkMmRjNGYwMjBhYmNjMGU2ZTk5YTNhNjA5NDY4NjRjYzQ0NDIyZmFmMTU0NDUzNDYxZTE5M2E2ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4TxSH-8OEadDFmjzkGNqJI2S8TTsk1TlZRIATkHufRg)

hmm, It is indeed correct management data is unavailable for the gbif sourced data while nests from iasset (nests.geojson) do have a management data. In the future all nests from natuurpunt will be uploaded automatically into iasset (currently in the pipeline). Changing to iAsset data only when the pipeline goes live will then result in us missing the small number of nests reported via iNaturalist (used to be more in past when we piggybacked on iNaturalist for management data). Therefor I think it is best to, leave it as is for now, but write code to be able to switch to only displaying nests from the nests.geojson only from a certain date<sup>1</sup> (when the Natuurpunt <-> iAssset pipeline goes live) onwards.  if this is possible ?

_<sup>1</sup>nests reported after this date should be displayed from iasset data only. Nests reported after this date from the gbif sourced data should no longer be displayed._

**Comment by SanderDevisscher** [comment]
> > in line graph below split lines for individuals & nests (or if to complex only nests)
> 
> Example below: Different linetype for nest and individual (all provinces) @SanderDevisscher Do you want this or remove the individual?
> 
> ![Screenshot from 2024-01-30 13-04-24](https://private-user-images.githubusercontent.com/22143743/300798491-086f7b09-1d8a-49cf-a1f8-be6b2b233bbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYzMjksIm5iZiI6MTcwNjY5NjAyOSwicGF0aCI6Ii8yMjE0Mzc0My8zMDA3OTg0OTEtMDg2ZjdiMDktMWQ4YS00OWNmLWExZjgtYmU2YjJiMjMzYmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEwMTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZGYwYTk1NzI4YTZhNjYwZDE1OGMxMGE5OTVhZGQwZDI5NWE4ODU4ODA1OTc3NDM5YTAzMGZjYjk4ZDJiNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EYrbs6Eu5fZb8Qt46xT67GbnfjP4L6C9Kh4nQvHC44s)

Its to cluttered as is! I would either drop the individuals or add like a unit dropdown to choose either. @timadriaens what do you think ?

**Comment by SanderDevisscher** [comment]
Can you add a management succes graph, like this:

![image](https://github.com/inbo/alien-species-portal/assets/16779320/c49e80ab-6158-4c8c-8a3c-48e75c3f2954)

It should be based on `nests.geojson` 

example code:
```
#figuur: Verhouding behandeling van nesten versus jaar.
data_to_plot <- nesten_VL_pr_r  %>%
  mutate(year = year(observation_time)) %>% 
  group_by(year, result) %>%
  summarise(number = n()) %>% 
  st_drop_geometry()

#NL
plot_treatment_per_year_nl <- ggplot(data = data_to_plot, aes(x = year, y = number, fill = result)) + 
  geom_bar(position = "stack", stat = "identity") + 
  labs(fill = "result") +
  scale_x_continuous("Jaar", labels = as.character(data_to_plot$year), breaks = data_to_plot$year) +
  ylab("Aantal nesten") +
  theme_set(theme_ggeffects())+
  theme(axis.text=element_text(size=15), axis.title= element_text(size=19))+
  theme(legend.title = element_text(size=17, face="bold")) +
  theme(legend.text = element_text(size=17, face="bold"))+
  scale_fill_manual(name = "Behandeling",
                    breaks = c("succesvol", "niet succesvol", "niet behandeld", "ongekend"),
                    labels = c("succesvol", "niet succesvol", "niet behandeld", "ongekend"),
                    values = c("darkorange2", "gold", "seagreen3", "dodgerblue2")) +
  guides(fill = guide_legend("Behandeling")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0))) 
```

**Comment by mvarewyck** [comment]
> nests reported after this date should be displayed from iasset data only. Nests reported after this date from the gbif sourced data should no longer be displayed.

Note: Date currently set at 31/12/2028, see [here](https://github.com/inbo/alien-species-portal/blob/fix_v1.0.0/alienSpecies/R/mapHeat.R#L67)

**Comment by mvarewyck** [comment]
> Can you add a management succes graph, like this:

The graph is included. 
@SanderDevisscher Do you already know a title and/or description? Then I'll add it to the translation file.

![newplot](https://github.com/inbo/alien-species-portal/assets/22143743/295ea7c4-6b7b-4b38-844b-0e752855fd72)

**Comment by mvarewyck** [comment]
>  add data lag disclaimer

@SanderDevisscher to be added to [translations file](https://github.com/inbo/aspbo/blob/mvarewyck-patch-1/data/output/UAT_direct/translations.csv)
* Disclaimer for active hotbeds is in row with `title_id == 'disclaimerVespa'`
* Disclaimer for all observations is in row with `title_id == 'management2_observed-mapHeat'`

![Screenshot from 2024-02-01 15-18-04](https://github.com/inbo/alien-species-portal/assets/22143743/75833a97-8e7e-49d9-a856-2cd077fc45d1)
