### ISSUE TITLE
permanent redirect when running createKeyData

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#65]
**Describe the bug**
When I run `createKeyData()` with the following parameters:
>  create key data
>  input:  "be_alientaxa_info.csv"
>  output: "keys.csv"
> createKeyData(dataDir = processingFilePath, bucket = bucket)

I get the following error (part of):
```
List of 6
 $ Code     : chr "PermanentRedirect"
 $ Message  : chr "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future "| __truncated__
```

**To Reproduce**
1. Go to 'inbo/aspbo/src/upload_processing_to_uat.R
2. Run 'L13 - L23'
3. Scroll down to 'L52' & run

**Expected behavior**
be_alientaxa_info.csv is processed as it should & no permanent direct error.

**Additional context**
Issue also occurs with:
- `createTabularData(dataDir = processingFilePath, type = "occurrence", bucket = bucket)`
- all the tests

probably fixed by adding the region parameter to save/load functions from the aws.S3 package (see https://github.com/inbo/alien-species-portal/pull/64/commits/13a6778484788f129dd5c525daf21ed16b0e3cba)

**Comment by mvarewyck** [comment]
> probably fixed by adding the region parameter to save/load functions from the aws.S3 package (see [13a6778](https://github.com/inbo/alien-species-portal/commit/13a6778484788f129dd5c525daf21ed16b0e3cba))

@SanderDevisscher I have already included the region parameter to all `aws.s3::s3save()` functions [here](https://github.com/inbo/alien-species-portal/pull/64/commits/13a6778484788f129dd5c525daf21ed16b0e3cba)
Maybe the script is still using an older version of the `alienSpecies` package?

**Comment by SanderDevisscher** [comment]
I think `s3write_using()` needs the region parameter as well in:

https://github.com/inbo/alien-species-portal/blob/ed5379bf4f5b9b8da1ddf01da742245aba7f5cfc/alienSpecies/R/data_create.R#L136-L138

**Comment by SanderDevisscher** [comment]
ps I'm using v0.0.5
