### ISSUE TITLE
bug when running createTabularData for indicators

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#66]
**Describe the bug**
When running `createTabularData(dataDir =  processingFilePath, type = "indicators", bucket = bucket)` I get the following error:

```
Error in strsplit(rawData$habitat, split = "|", fixed = TRUE) :
non-character argument
```

**To Reproduce**

1. Steps to reproduce the behavior:
2. Go to 'inbo/aspbo/src/upload_processing_to_uat.R
3. Run 'L13 - L23'
4. Scroll down to 'L66' & run
5. See error

**Expected behavior**
"data_input_checklist_indicators_processed.RData" is updated correctly. 

**Additional context**
I'm using the alienSpecies v0.0.5

**Comment by Yingjie-ZhangOA** [comment]
error due to there is no column `habitat`
This error happened after the  following change took place
```
Files changed:
M	data/output/UAT_processing/data_input_checklist_indicators.tsv
M	data/output/UAT_processing/griis_checklist_version.txt
```

**Comment by SanderDevisscher** [comment]
I've added the column habitat to `data_input_checklist_indicators.tsv` but now I get the following error:
```
Error in createTabularData(dataDir = processingFilePath, type = "indicators",  : 
  New habitats detected. Add relevant columns in loadTabularData()
```

can you guide me to where I need to add these columns ?

**Comment by Yingjie-ZhangOA** [comment]
Can you put `data_input_checklist_indicators.tsv` on bucket (just tried the current one, cannot reproduce the error), so I can look into this issue.

**Comment by Yingjie-ZhangOA** [comment]
I downloaded data from bucket and ran `createTabularData( type = "indicators")`, but I cannot reproduce the error. The error message will be shown if in `habitat` there is something else than `"marine", "freshwater", "terrestrial", NA`. Is `data_input_checklist_indicators.tsv` on bucket?

**Comment by Yingjie-ZhangOA** [comment]
I cannot reproduce this error, can you instruct me where the `data_input_checklist_indicators.tsv` file in your test is located?

**Comment by SanderDevisscher** [comment]
I've updated the file at data/output/UAT_processing/ on the 55-[bug]
habitat column missing from griis checklist - branch.

Op ma 18 dec. 2023 16:02 schreef Yingjie Zhang ***@***.***>:

**Comment by Yingjie-ZhangOA** [comment]
commit 22650bc solves the issue
@mvarewyck  `loadTabularData()` doesn't do any data manipulation anymore, we should change the message accordingly.

**Comment by mvarewyck** [comment]
> @mvarewyck `loadTabularData()` doesn't do any data manipulation anymore, we should change the message accordingly.

Done https://github.com/inbo/alien-species-portal/commit/295d8f261ce2f97890955e2c169d1ce82229df66
