### ISSUE TITLE
[Enhancement] improve taxa table

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#72]
# Feature title
global indicators > taxa > taxa table

# Description
- [ ] add venecular name per language (empty if not available)
- [x] all filters should have the same dimensions & aligned positioning
- [x] all filters should have the same font (size)
- [ ] add disclaimer (@timadriaens @bramdhondt @SanderDevisscher will provide text)
- [x] "more" icons should be same size & aligned positioning
- [x] "more" icons should become yellow when 4 main tabs (Observations, Indicators, Reporting & Management) are present

# Needed changes in backoffice
- [x] inbo/aspbo#84

**Comment by mvarewyck** [comment]
>  add vernacular_name_nl, vernacular_name_fr, vernacular_name_en to input data (which file ?)

@SanderDevisscher It should be added to "data_input_checklist_indicators.tsv"
Please inform me if done and share an example (e.g. first 10 records), I will need to update the createTabularData() function to pick up these new columns correctly.
