### ISSUE TITLE
[Feature request] Add invasion history maps

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#73]
**Is your feature request related to a problem? Please describe.**
No, just a new feature as requested by @timadriaens 

**Describe the solution you'd like**
A stack of maps comparing the current year of invasion with the 2 prior periodes of 3 years (map current year (2024) + map current year -1 (2023) <-> current year - 4 (2020) + map current year -5 (2019) <-> current year - 9 (2016))

**Describe alternatives you've considered**
not relevant 

**Additional context**
example for vespa, _note years do not match request_.
![image](https://github.com/inbo/alien-species-portal/assets/16779320/61cf672a-15aa-4c58-bff8-1b63b651bd5a)

@SanderDevisscher add code example

**Comment by SanderDevisscher** [comment]
for all species with management

**Comment by mvarewyck** [comment]
Some more questions

* Static or interactive maps? Interactive can be slow and how to handle zooming?
* Region levels: choices are municipalities and provinces. If municipalities, need border for provinces?
* Same options as current maps: legend placement, show/hide globe, unit, source

I checked: Oxyura jamaicensis has **no info** on municipalities and provinces. https://github.com/inbo/aspbo/issues/53#issuecomment-1921085756

Current graphs and filters (already in the app):

![Screenshot from 2024-02-01 16-36-48](https://github.com/inbo/alien-species-portal/assets/22143743/c58b68bc-c5c8-4056-9905-1bcff567e2d2)
![Screenshot from 2024-02-01 16-35-55](https://github.com/inbo/alien-species-portal/assets/22143743/d68d42b7-f9c2-4f95-995c-e09762a20b66)

**Comment by SanderDevisscher** [comment]
> Some more questions

> 1. Static or interactive maps? Interactive can be slow and how to handle zooming?
> 2. Region levels: choices are municipalities and provinces. If municipalities, need border for provinces?
> 3. Same options as current maps: legend placement, show/hide globe, unit, source

1. static is ok
2. If municipalities, need border for provinces? => yes please
3. Yes

**Comment by mvarewyck** [comment]
Example output for Vespa Velutina
@SanderDevisscher @timadriaens 

![Screenshot from 2024-02-20 14-53-43](https://github.com/inbo/alien-species-portal/assets/22143743/e2ff4afe-a142-4f1b-be05-e5a951fdb043)
![Screenshot from 2024-02-20 14-45-35](https://github.com/inbo/alien-species-portal/assets/22143743/8c03f113-93f8-44ea-92ed-75a4ab0d9a1e)

**Comment by SanderDevisscher** [comment]
@mvarewyck can you add a region (flanders, wallonia, etc...) filter ?

**Comment by SanderDevisscher** [comment]
@timadriaens we need to think about usefull "levels"

**Comment by mvarewyck** [comment]
> @mvarewyck can you add a region (flanders, wallonia, etc...) filter ?

We have a region filter now at the top of the page which applies for all graphs.

![Screenshot from 2024-02-22 09-35-41](https://github.com/inbo/alien-species-portal/assets/22143743/4f9f21b2-24d5-4f65-be0c-f05cd091daa8)
![Screenshot from 2024-02-22 09-35-28](https://github.com/inbo/alien-species-portal/assets/22143743/af26103e-1d09-4bff-bceb-14cea6f58be8)

**Comment by SanderDevisscher** [comment]
Perfect

**Comment by SanderDevisscher** [comment]
@mvarewyck which sources did you use for the respective maps ?

**Comment by SanderDevisscher** [comment]
I'm thinking this might better fit under indicators or observation than management since it should display the number of observations in resp. periods 🤔 

@soriadelva what do you think ?

**Comment by soriadelva** [comment]
> I'm thinking this might better fit under indicators or observation than management since it should display the number of observations in resp. periods 🤔
> 
> @soriadelva what do you think ?

Agreed, I feel that it fits well under indicators given that checklist-based indicators already includes graphs that show the number of introduced species in BE as a function of time, which is a bit related to this (without the spatial component and restricted time periods).

**Comment by mvarewyck** [comment]
> @mvarewyck which sources did you use for the respective maps ?

@SanderDevisscher @soriadelva I use management data.
* For Vespa velutina it is the total sum of points, nesten and beheerde nesten (same as in the map at top of mgt page)
* For Lithobates catesbeianus it is the total count from GBIF (Lithobates_catesbeianus.csv in S3 bucket)

We can change it to any type of source; the data only needs to contain year and region columns (count can be 1 per row).

**Comment by SanderDevisscher** [comment]
Since we want to display the invasion history of a species I think we need to use the observations instead of management. 
So the same data source as the observation maps. 

- [ ] @mvarewyck highlight changes needed to input files
- [ ] @SanderDevisscher @soriadelva provide modified input files
- [ ] @mvarewyck move maps to indicators subtab

**Comment by mvarewyck** [comment]
@SanderDevisscher Which **spatial regions** do you want to show for the invasion maps? 

(1) Municipalities & provinces like in the current *invasion* maps -> need to enrich data file [`be_alientaxa_cube.csv`](https://github.com/inbo/aspbo/blob/uat/data/output/UAT_processing/be_alientaxa_cube.csv) with columns
  - `NAAM`: municipality name
  - `provincie`: province name

(2) UTM 1x1 and 10x10 squares like in the current *observation* maps -> no change to the input data needed

**Comment by SanderDevisscher** [comment]
I think all 4 options should be possible.

**Comment by mvarewyck** [comment]
> [ ] @SanderDevisscher @soriadelva provide modified input files

@soriadelva I saw this [PR](https://github.com/inbo/aspbo/pull/201) but it enriches the reporting files instead of observations? For this issue, we need to enrich [be_alientaxa_cube.csv](https://github.com/inbo/aspbo/blob/uat/data/output/UAT_processing/be_alientaxa_cube.csv)

**Comment by soriadelva** [comment]
> > [ ] @SanderDevisscher @soriadelva provide modified input files
> 
> @soriadelva I saw this [PR](https://github.com/inbo/aspbo/pull/201) but it enriches the reporting files instead of observations? For this issue, we need to enrich [be_alientaxa_cube.csv](https://github.com/inbo/aspbo/blob/uat/data/output/UAT_processing/be_alientaxa_cube.csv)

@mvarewyck thanks for noticing, I have now done a left join with the be_alientaxa_cube and the utm1 file and saved this as a .csv. However, this file seems  too big to push to Github. How should I best add this file to the repo and is .csv okay (maybe .gpkg would be better?)

**Comment by mvarewyck** [comment]
> > > [ ] @SanderDevisscher @soriadelva provide modified input files
> > 
> > 
> > @soriadelva I saw this [PR](https://github.com/inbo/aspbo/pull/201) but it enriches the reporting files instead of observations? For this issue, we need to enrich [be_alientaxa_cube.csv](https://github.com/inbo/aspbo/blob/uat/data/output/UAT_processing/be_alientaxa_cube.csv)
> 
> @mvarewyck thanks for noticing, I have now done a left join with the be_alientaxa_cube and the utm1 file and saved this as a .csv. However, this file seems too big to push to Github. How should I best add this file to the repo and is .csv okay (maybe .gpkg would be better?)

@soriadelva I don't think .gpkg will be smaller than .csv. The file you upload will be processed and reduced in size before uploading it to S3 as parquet file. How big is your file now? You could consider using [Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage)

**Comment by soriadelva** [comment]
> > > > [ ] @SanderDevisscher @soriadelva provide modified input files
> > > 
> > > 
> > > @soriadelva I saw this [PR](https://github.com/inbo/aspbo/pull/201) but it enriches the reporting files instead of observations? For this issue, we need to enrich [be_alientaxa_cube.csv](https://github.com/inbo/aspbo/blob/uat/data/output/UAT_processing/be_alientaxa_cube.csv)
> > 
> > 
> > @mvarewyck thanks for noticing, I have now done a left join with the be_alientaxa_cube and the utm1 file and saved this as a .csv. However, this file seems too big to push to Github. How should I best add this file to the repo and is .csv okay (maybe .gpkg would be better?)
> 
> @soriadelva I don't think .gpkg will be smaller than .csv. The file you upload will be processed and reduced in size before uploading it to S3 as parquet file. How big is your file now? You could consider using [Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage)

@mvarewyck it's over 316 MB, I tried to use Git LFS but got the following error when pushing:
`batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
`

**Comment by SanderDevisscher** [comment]
@mvarewyck @soriadelva i think we have to look into storing the file directly on the S3-bucket thus bypassing github

**Comment by soriadelva** [comment]
> @mvarewyck @soriadelva i think we have to look into storing the file directly on the S3-bucket thus bypassing github

@SanderDevisscher, yes that would fix it 👍

**Comment by mvarewyck** [comment]
I have created the graphs for all region levels. Example for Muntiacus reevesi.

* For gemeentes/provinces we show all regions, irrespective of whether there were observations. 
* For gemeentes we show province borders in black
![example_communes](https://github.com/inbo/alien-species-portal/assets/22143743/cead8896-c303-48ad-bbd5-4138af762a29)

* For the UTM I would only display the ones that have actual observations (like we currently do in the tab 'Observations'). Especially for UTM1 it is not clear if we show all blocks.
* For the UTM we show gewest borders in black, for reference
![example_cell_code10](https://github.com/inbo/alien-species-portal/assets/22143743/a0e4d7bc-4d06-4e4e-b5bc-7307bc9a5105)

**Comment by soriadelva** [comment]
> I have created the graphs for all region levels. Example for Muntiacus reevesi.
> 
> * For gemeentes/provinces we show all regions, irrespective of whether there were observations.
> * For gemeentes we show province borders in black
>   ![example_communes](https://private-user-images.githubusercontent.com/22143743/347417137-cead8896-c303-48ad-bbd5-4138af762a29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTgwMDEsIm5iZiI6MTcyMDYxNzcwMSwicGF0aCI6Ii8yMjE0Mzc0My8zNDc0MTcxMzctY2VhZDg4OTYtYzMwMy00OGFkLWJiZDUtNDEzOGFmNzYyYTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEzMjE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NDUzZmE3ZjE0MWIyZThjMWRkOGRhNmNkNDUzYmU1ZWVmNGI2ODI3OTQ5ZTFmZmQyZmU3MjI4NDQzMTA5NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aNAYmo2pMAmvci7gfjTlXf2632NnfNUWWz6x7qp2KVo)
> * For the UTM I would only display the ones that have actual observations (like we currently do in the tab 'Observations'). Especially for UTM1 it is not clear if we show all blocks.
> * For the UTM we show gewest borders in black, for reference
>   ![example_cell_code10](https://private-user-images.githubusercontent.com/22143743/347420157-a0e4d7bc-4d06-4e4e-b5bc-7307bc9a5105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTgwMDEsIm5iZiI6MTcyMDYxNzcwMSwicGF0aCI6Ii8yMjE0Mzc0My8zNDc0MjAxNTctYTBlNGQ3YmMtNGQwNi00ZTRlLWI1YmMtNzMwN2JjOWE1MTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEzMjE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhYTNlM2M4NzZhMjhmYjJhYmUwYWNiNzAxMGE3OTcwYjQ0MTQ1ODQxZDdmZmYyZjA1NThiMzhiODU2YmM2YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8rsbfhY8Eu7vE3OoAl8kWNDMsrWQ1huAhx5N6D7mY_A)

I think it looks great 👍
