### ISSUE TITLE
[Feature request] add make report functionality

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#75]
**Describe the solution you'd like**
Add a floating button like on dashboard page of grofwild to the species indicator page. When this button is pressed all graphs & maps from all tabs from 1 species should be exported as a pdf. Also like the grofwild the settings of the filters should be included in the export.

**Comment by mvarewyck** [comment]
@SanderDevisscher What do we include for plots that are 'hidden' in the app? For example, when selecting a species and not yet clicking on all subtabs, we don't know which parameters to select for the plots that are not yet shown to the user (hidden plots). Options on how to include these plots in the report:

1. Include the plot with default parameters (year, region level etc)
2. Don't include the plot with message to first choose parameters in the app

**Comment by SanderDevisscher** [comment]
I would go for option 1

**Comment by mvarewyck** [comment]
TODO: If no parameters selected by the user, print the default values in the report as used in the shown graph
