### ISSUE TITLE
[Feature request] integrate climate risk maps

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#77]
**Describe the solution you'd like**
Some species have ready made climate risk maps. These maps should be placed under the more tab of the species page. 

Currently these riskmaps reside here https://github.com/trias-project/risk-maps/tree/main and they are currently hosted here https://trias-project.github.io/risk-maps/. 

From what I can understand of the naming of the files, the modeled data is stored as geotiffs in this folder "./public/geotiffs".
the naming convention is as follows: be_<gbif taxonkey>_ followed by 

| appendix              | meaning                                                                                                                            |
|-----------------------|------------------------------------------------------------------------------------------------------------------------------------|
| hist.4326.tif         | risk map of model based on historical climate data                                                                                 |
| hist_conf.4326.tif    | confidence map of model based on historical climate data                                                                           |
| rcp%xy%.4326.tif      | risk map of model based on RCP %x.y% forecast of future climate between 2040-2070                                                  |
| rcp%xy%_conf.4326.tif | confidence map of model based on RCP %x.y% forecast of the future climate between 2040-2070                                        |
| rcp%xy%_diff.4326.tif | difference map between the model based on historical climate data & the RCP %x.y% forecast of the future climate between 2040-2070 |

@mvarewyck can you look into how we can best integrate these "webpages" ?   

note we hope to increase the number of species with a risk map.

**Comment by mvarewyck** [comment]
I tried to follow the same structure & options as the Trias tool.
@SanderDevisscher Trias tool also has these options, do we need any?

* data layer opacity slider
* show option: modelled data/occurrence data/both -> currently we only plot modelled data and show this tabpanel if there are modelled data (tif files)
* overlays: none/ecoregions/bioregions/river basins -> currently we always show 'gewesten' layer like we do for all plots

Scenario 1: there are modelled data

![Screenshot from 2024-02-06 14-36-52](https://github.com/inbo/alien-species-portal/assets/22143743/e74701ff-518a-48d6-bcf0-8c40ad5533f5)

Scenario 2: there are no modelled data

![Screenshot from 2024-02-06 14-37-09](https://github.com/inbo/alien-species-portal/assets/22143743/547a02a0-83f8-482e-91a9-9f02814d6a1a)

**Comment by SanderDevisscher** [comment]
@mvarewyck This allready looks very good. 
in case of species that miss all model data the option "risk maps" should not be activated.

**Comment by mvarewyck** [comment]
> in case of species that miss all model data the option "risk maps" should not be activated.

to clarify: 
* if for the species there are no modelled data at all, the "risk maps" is not activated. 
* if for a species there are modelled data, but not for some specific scenarios (e.g. wrong tif file format, requesting difference while not selecting RCP scenario), there is a disclaimer as shown in 'Scenario 2' above

**Comment by SanderDevisscher** [comment]
Exactly

Op di 6 feb. 2024 16:34 schreef Machteld Varewyck ***@***.***
