### ISSUE TITLE
[BUG] App crashes almost immediately when selecting global indicators

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#80]
**Describe the bug**
When the app has started and you click on the global indicator tile you get a timeout almost immediately.

**To Reproduce**
1. Go to 'exoten-uat.inbo.be'
2. Click on 'Global Indicators'
3. Wait for page to load

**Expected behavior**
The global indicators page load without crash

**Screenshots**
![image](https://github.com/inbo/alien-species-portal/assets/16779320/0879e122-0567-4164-812e-2ce2947921ec)

**Additional context**
@TheJenne18 looked at the docker logs of the application and it seems to get a "abort by user" command while none was given.

**Comment by mvarewyck** [comment]
@SanderDevisscher @TheJenne18 Which git commit did you use to build the docker image?

**Comment by SanderDevisscher** [comment]
@TheJenne18 can you answer this question ? I can't find any mention of hashes concerning the exoten portaal & no feature like at faunabeheer.inbo.be to determine the hash has been implemented yet (see #82).

**Comment by SanderDevisscher** [comment]
the deployed version is v0.0.5.
