### ISSUE TITLE
[Enhancement] allow custom bins

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#83]

**Comment by mvarewyck** [comment]
Include options:

* Bins: default (current implementation) or user-defined

If modified, extra options

* number of bins: 5 to 8 (slider)
@SanderDevisscher how to define the bins: based on quantiles (uniform distr. of no. of observations); equal-sized bins; other?

Example implementation in another context:

![Screenshot from 2024-03-21 10-16-20](https://github.com/inbo/alien-species-portal/assets/22143743/c4082637-d637-4081-b227-f363fd0e6f64)
