### ISSUE TITLE
[Enhancement] add year slider to GAM indicators

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#85]
# Feature title
species information > indicators > Emergence status (GAM) - Observations
species information > indicators > Emergence status (GAM) - Occupancy (after #84) 

# Description
add a year range slider which filters the input data for the GAMs. 
Default (current year - 3) - (current year -1). 

# (Optional) Needed changes in backoffice
none

**Comment by mvarewyck** [comment]
@SanderDevisscher Which years you want to define?
* [eval_years](https://github.com/trias-project/trias/blob/main/R/apply_gam.R#L9-L10): reference period for the GAM estimation in trias
* year: subset the data wrt to these years

**Comment by SanderDevisscher** [comment]
> @SanderDevisscher Which years you want to define?
> 
> * [eval_years](https://github.com/trias-project/trias/blob/main/R/apply_gam.R#L9-L10): reference period for the GAM estimation in trias

I mean this yes. So a slider to change the `eval_years` parameter of the `apply_gam()` function.

> * year: subset the data wrt to these years

not this

**Comment by mvarewyck** [comment]
> > @SanderDevisscher Which years you want to define?
> > 
> > * [eval_years](https://github.com/trias-project/trias/blob/main/R/apply_gam.R#L9-L10): reference period for the GAM estimation in trias
> 
> I mean this yes. So a slider to change the `eval_years` parameter of the `apply_gam()` function.
> 
> > * year: subset the data wrt to these years
> 
> not this

The parameter `eval_years` doesn't have any effect on the results (output data + plot) we show. I have just tested using an example from trias. (It does change the returned `em_summary`, but this we don't use in the app)

```{r}
    library(trias)
    library(dplyr)
    df_gam <- tibble(
      taxonKey = rep(3003709, 24),
      canonicalName = rep("Rosa glauca", 24),
      year = seq(1995, 2018),
      n = c(
        1, 1, 0, 0, 0, 2, 0, 0, 1, 3, 1, 2, 0, 5, 0, 5, 4, 2, 1,
        1, 3, 3, 8, 10
      ),
      n_class = c(
        229, 555, 1116, 939, 919, 853, 442, 532, 623, 1178, 732, 371, 1053,
        1001, 1550, 1142, 1076, 1310, 922, 1773, 1637,
        1866, 2234, 2013
      )
    )
    # apply GAM to n without baseline as covariate
    result1 <- apply_gam(df_gam,
      y_var = "n",
      eval_years = 2018,
      taxon_key = 3003709,
      name = "Rosa glauca",
      verbose = TRUE
    )
    result1$plot
    
    result2 <- apply_gam(df_gam,
      y_var = "n",
      eval_years = 2000,
      taxon_key = 3003709,
      name = "Rosa glauca",
      verbose = TRUE
    )
    all(result2$output == result1$output)
    # [1] "Analyzing: Rosa glauca(3003709)"
    # [1] "Analyzing: Rosa glauca(3003709)"
    # [1] TRUE

```

This is the expected behavior following the [documentation of trias](https://github.com/trias-project/trias/blob/main/R/apply_gam.R#L67-L80)

@SanderDevisscher Could you explain what you want in the app?

**Comment by SanderDevisscher** [comment]
@mvarewyck in that case we can drop the year slider
