### ISSUE TITLE
[Enhancement] add dynamic title to GAMs

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#87]
# Feature title
species information > indicators > Emergence status (GAM) - Observations
species information > indicators > Emergence status (GAM) - Occupancy (after https://github.com/inbo/alien-species-portal/issues/84)

# Description
It would be nice to add a dynamic title to the GAMs. 
I would suggest the following:

"%_GAM type_% - %_Sciencetific name_% (%_taxonKey_%) - %_additional parameters seperated by &_% from %_min year slider_% to %_max year slider_% in %_selected region if not all else "Belgium"_%"

so for the observations GAM for Vespa velutina corrected for observer bias in protected areas from 2016 tot 2023 in flanders this would become:
_"Observations GAM - Vespa velutina(1311477) - corrected for observer bias & protected areas from 2016 to 2023 in flanders"_

# (Optional) Needed changes in backoffice
- [ ] new rows should be added to translation file @mvarewyck 
- [x] translations should be provided @SanderDevisscher @soriadelva @bramdhondt

**Comment by mvarewyck** [comment]
Also include legend enhancement: https://github.com/inbo/aspbo/issues/92
