### ISSUE TITLE
[Enhancement] The colors of the observation graph change upon changing the year range

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/alien-species-portal#89]
# Feature title
Species information > observations

# Description
The graph below the map changes color when you change the year range. 

todo add screenshots

**Comment by mvarewyck** [comment]
@SanderDevisscher You mean the legend colors should be fixed? Example below for Abies Alba: Flanders switches from green to blue

![Screenshot from 2024-04-12 16-56-01](https://github.com/inbo/alien-species-portal/assets/22143743/7fb82a6b-d23f-4d21-9737-2bf0f5e10dc9)

![Screenshot from 2024-04-12 16-56-13](https://github.com/inbo/alien-species-portal/assets/22143743/f6215527-5613-49d5-9cf8-0bfc0d040f21)

**Comment by SanderDevisscher** [comment]
exactly
